// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

//go:build test_unit || test_integration

package go_librespot

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockAudioSource creates a new instance of MockAudioSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAudioSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAudioSource {
	mock := &MockAudioSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAudioSource is an autogenerated mock type for the AudioSource type
type MockAudioSource struct {
	mock.Mock
}

type MockAudioSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAudioSource) EXPECT() *MockAudioSource_Expecter {
	return &MockAudioSource_Expecter{mock: &_m.Mock}
}

// PositionMs provides a mock function for the type MockAudioSource
func (_mock *MockAudioSource) PositionMs() int64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PositionMs")
	}

	var r0 int64
	if returnFunc, ok := ret.Get(0).(func() int64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int64)
	}
	return r0
}

// MockAudioSource_PositionMs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PositionMs'
type MockAudioSource_PositionMs_Call struct {
	*mock.Call
}

// PositionMs is a helper method to define mock.On call
func (_e *MockAudioSource_Expecter) PositionMs() *MockAudioSource_PositionMs_Call {
	return &MockAudioSource_PositionMs_Call{Call: _e.mock.On("PositionMs")}
}

func (_c *MockAudioSource_PositionMs_Call) Run(run func()) *MockAudioSource_PositionMs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAudioSource_PositionMs_Call) Return(n int64) *MockAudioSource_PositionMs_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockAudioSource_PositionMs_Call) RunAndReturn(run func() int64) *MockAudioSource_PositionMs_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function for the type MockAudioSource
func (_mock *MockAudioSource) Read(float32s []float32) (int, error) {
	ret := _mock.Called(float32s)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]float32) (int, error)); ok {
		return returnFunc(float32s)
	}
	if returnFunc, ok := ret.Get(0).(func([]float32) int); ok {
		r0 = returnFunc(float32s)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]float32) error); ok {
		r1 = returnFunc(float32s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAudioSource_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockAudioSource_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - float32s []float32
func (_e *MockAudioSource_Expecter) Read(float32s interface{}) *MockAudioSource_Read_Call {
	return &MockAudioSource_Read_Call{Call: _e.mock.On("Read", float32s)}
}

func (_c *MockAudioSource_Read_Call) Run(run func(float32s []float32)) *MockAudioSource_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []float32
		if args[0] != nil {
			arg0 = args[0].([]float32)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAudioSource_Read_Call) Return(n int, err error) *MockAudioSource_Read_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockAudioSource_Read_Call) RunAndReturn(run func(float32s []float32) (int, error)) *MockAudioSource_Read_Call {
	_c.Call.Return(run)
	return _c
}

// SetPositionMs provides a mock function for the type MockAudioSource
func (_mock *MockAudioSource) SetPositionMs(n int64) error {
	ret := _mock.Called(n)

	if len(ret) == 0 {
		panic("no return value specified for SetPositionMs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64) error); ok {
		r0 = returnFunc(n)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAudioSource_SetPositionMs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPositionMs'
type MockAudioSource_SetPositionMs_Call struct {
	*mock.Call
}

// SetPositionMs is a helper method to define mock.On call
//   - n int64
func (_e *MockAudioSource_Expecter) SetPositionMs(n interface{}) *MockAudioSource_SetPositionMs_Call {
	return &MockAudioSource_SetPositionMs_Call{Call: _e.mock.On("SetPositionMs", n)}
}

func (_c *MockAudioSource_SetPositionMs_Call) Run(run func(n int64)) *MockAudioSource_SetPositionMs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAudioSource_SetPositionMs_Call) Return(err error) *MockAudioSource_SetPositionMs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAudioSource_SetPositionMs_Call) RunAndReturn(run func(n int64) error) *MockAudioSource_SetPositionMs_Call {
	_c.Call.Return(run)
	return _c
}
