// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: spotify/metadata/contentratings/v1/content_ratings.proto

package contentratingsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContentRatingTag int32

const (
	ContentRatingTag_CONTENT_RATING_TAG_UNSPECIFIED      ContentRatingTag = 0
	ContentRatingTag_CONTENT_RATING_TAG_EXPLICIT         ContentRatingTag = 1
	ContentRatingTag_CONTENT_RATING_TAG_MOGEF_19         ContentRatingTag = 2
	ContentRatingTag_CONTENT_RATING_TAG_SPOTIFY_18_PLUS  ContentRatingTag = 3
	ContentRatingTag_CONTENT_RATING_TAG_EROTIC           ContentRatingTag = 4
	ContentRatingTag_CONTENT_RATING_TAG_NOT_FOR_CHILDREN ContentRatingTag = 5
)

// Enum value maps for ContentRatingTag.
var (
	ContentRatingTag_name = map[int32]string{
		0: "CONTENT_RATING_TAG_UNSPECIFIED",
		1: "CONTENT_RATING_TAG_EXPLICIT",
		2: "CONTENT_RATING_TAG_MOGEF_19",
		3: "CONTENT_RATING_TAG_SPOTIFY_18_PLUS",
		4: "CONTENT_RATING_TAG_EROTIC",
		5: "CONTENT_RATING_TAG_NOT_FOR_CHILDREN",
	}
	ContentRatingTag_value = map[string]int32{
		"CONTENT_RATING_TAG_UNSPECIFIED":      0,
		"CONTENT_RATING_TAG_EXPLICIT":         1,
		"CONTENT_RATING_TAG_MOGEF_19":         2,
		"CONTENT_RATING_TAG_SPOTIFY_18_PLUS":  3,
		"CONTENT_RATING_TAG_EROTIC":           4,
		"CONTENT_RATING_TAG_NOT_FOR_CHILDREN": 5,
	}
)

func (x ContentRatingTag) Enum() *ContentRatingTag {
	p := new(ContentRatingTag)
	*p = x
	return p
}

func (x ContentRatingTag) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContentRatingTag) Descriptor() protoreflect.EnumDescriptor {
	return file_spotify_metadata_contentratings_v1_content_ratings_proto_enumTypes[0].Descriptor()
}

func (ContentRatingTag) Type() protoreflect.EnumType {
	return &file_spotify_metadata_contentratings_v1_content_ratings_proto_enumTypes[0]
}

func (x ContentRatingTag) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContentRatingTag.Descriptor instead.
func (ContentRatingTag) EnumDescriptor() ([]byte, []int) {
	return file_spotify_metadata_contentratings_v1_content_ratings_proto_rawDescGZIP(), []int{0}
}

type ContentRatings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []ContentRatingTag     `protobuf:"varint,1,rep,packed,name=tags,proto3,enum=spotify.metadata.contentratings.v1.ContentRatingTag" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentRatings) Reset() {
	*x = ContentRatings{}
	mi := &file_spotify_metadata_contentratings_v1_content_ratings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentRatings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentRatings) ProtoMessage() {}

func (x *ContentRatings) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_metadata_contentratings_v1_content_ratings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentRatings.ProtoReflect.Descriptor instead.
func (*ContentRatings) Descriptor() ([]byte, []int) {
	return file_spotify_metadata_contentratings_v1_content_ratings_proto_rawDescGZIP(), []int{0}
}

func (x *ContentRatings) GetTags() []ContentRatingTag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ContentRatingTagWithMarkets struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           ContentRatingTag       `protobuf:"varint,1,opt,name=tag,proto3,enum=spotify.metadata.contentratings.v1.ContentRatingTag" json:"tag,omitempty"`
	Markets       []string               `protobuf:"bytes,2,rep,name=markets,proto3" json:"markets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentRatingTagWithMarkets) Reset() {
	*x = ContentRatingTagWithMarkets{}
	mi := &file_spotify_metadata_contentratings_v1_content_ratings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentRatingTagWithMarkets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentRatingTagWithMarkets) ProtoMessage() {}

func (x *ContentRatingTagWithMarkets) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_metadata_contentratings_v1_content_ratings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentRatingTagWithMarkets.ProtoReflect.Descriptor instead.
func (*ContentRatingTagWithMarkets) Descriptor() ([]byte, []int) {
	return file_spotify_metadata_contentratings_v1_content_ratings_proto_rawDescGZIP(), []int{1}
}

func (x *ContentRatingTagWithMarkets) GetTag() ContentRatingTag {
	if x != nil {
		return x.Tag
	}
	return ContentRatingTag_CONTENT_RATING_TAG_UNSPECIFIED
}

func (x *ContentRatingTagWithMarkets) GetMarkets() []string {
	if x != nil {
		return x.Markets
	}
	return nil
}

type ContentRatingsWithMarket struct {
	state                 protoimpl.MessageState         `protogen:"open.v1"`
	RatingTagsWithMarkets []*ContentRatingTagWithMarkets `protobuf:"bytes,1,rep,name=rating_tags_with_markets,json=ratingTagsWithMarkets,proto3" json:"rating_tags_with_markets,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ContentRatingsWithMarket) Reset() {
	*x = ContentRatingsWithMarket{}
	mi := &file_spotify_metadata_contentratings_v1_content_ratings_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentRatingsWithMarket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentRatingsWithMarket) ProtoMessage() {}

func (x *ContentRatingsWithMarket) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_metadata_contentratings_v1_content_ratings_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentRatingsWithMarket.ProtoReflect.Descriptor instead.
func (*ContentRatingsWithMarket) Descriptor() ([]byte, []int) {
	return file_spotify_metadata_contentratings_v1_content_ratings_proto_rawDescGZIP(), []int{2}
}

func (x *ContentRatingsWithMarket) GetRatingTagsWithMarkets() []*ContentRatingTagWithMarkets {
	if x != nil {
		return x.RatingTagsWithMarkets
	}
	return nil
}

var File_spotify_metadata_contentratings_v1_content_ratings_proto protoreflect.FileDescriptor

const file_spotify_metadata_contentratings_v1_content_ratings_proto_rawDesc = "" +
	"\n" +
	"8spotify/metadata/contentratings/v1/content_ratings.proto\x12\"spotify.metadata.contentratings.v1\"Z\n" +
	"\x0eContentRatings\x12H\n" +
	"\x04tags\x18\x01 \x03(\x0e24.spotify.metadata.contentratings.v1.ContentRatingTagR\x04tags\"\x7f\n" +
	"\x1bContentRatingTagWithMarkets\x12F\n" +
	"\x03tag\x18\x01 \x01(\x0e24.spotify.metadata.contentratings.v1.ContentRatingTagR\x03tag\x12\x18\n" +
	"\amarkets\x18\x02 \x03(\tR\amarkets\"\x94\x01\n" +
	"\x18ContentRatingsWithMarket\x12x\n" +
	"\x18rating_tags_with_markets\x18\x01 \x03(\v2?.spotify.metadata.contentratings.v1.ContentRatingTagWithMarketsR\x15ratingTagsWithMarkets*\xe8\x01\n" +
	"\x10ContentRatingTag\x12\"\n" +
	"\x1eCONTENT_RATING_TAG_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bCONTENT_RATING_TAG_EXPLICIT\x10\x01\x12\x1f\n" +
	"\x1bCONTENT_RATING_TAG_MOGEF_19\x10\x02\x12&\n" +
	"\"CONTENT_RATING_TAG_SPOTIFY_18_PLUS\x10\x03\x12\x1d\n" +
	"\x19CONTENT_RATING_TAG_EROTIC\x10\x04\x12'\n" +
	"#CONTENT_RATING_TAG_NOT_FOR_CHILDREN\x10\x05B\xc5\x02\n" +
	"&com.spotify.metadata.contentratings.v1B\x13ContentRatingsProtoP\x01Z[github.com/devgianlu/go-librespot/proto/spotify/metadata/contentratings/v1;contentratingsv1\xa2\x02\x03SMC\xaa\x02\"Spotify.Metadata.Contentratings.V1\xca\x02\"Spotify\\Metadata\\Contentratings\\V1\xe2\x02.Spotify\\Metadata\\Contentratings\\V1\\GPBMetadata\xea\x02%Spotify::Metadata::Contentratings::V1b\x06proto3"

var (
	file_spotify_metadata_contentratings_v1_content_ratings_proto_rawDescOnce sync.Once
	file_spotify_metadata_contentratings_v1_content_ratings_proto_rawDescData []byte
)

func file_spotify_metadata_contentratings_v1_content_ratings_proto_rawDescGZIP() []byte {
	file_spotify_metadata_contentratings_v1_content_ratings_proto_rawDescOnce.Do(func() {
		file_spotify_metadata_contentratings_v1_content_ratings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spotify_metadata_contentratings_v1_content_ratings_proto_rawDesc), len(file_spotify_metadata_contentratings_v1_content_ratings_proto_rawDesc)))
	})
	return file_spotify_metadata_contentratings_v1_content_ratings_proto_rawDescData
}

var file_spotify_metadata_contentratings_v1_content_ratings_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_spotify_metadata_contentratings_v1_content_ratings_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_spotify_metadata_contentratings_v1_content_ratings_proto_goTypes = []any{
	(ContentRatingTag)(0),               // 0: spotify.metadata.contentratings.v1.ContentRatingTag
	(*ContentRatings)(nil),              // 1: spotify.metadata.contentratings.v1.ContentRatings
	(*ContentRatingTagWithMarkets)(nil), // 2: spotify.metadata.contentratings.v1.ContentRatingTagWithMarkets
	(*ContentRatingsWithMarket)(nil),    // 3: spotify.metadata.contentratings.v1.ContentRatingsWithMarket
}
var file_spotify_metadata_contentratings_v1_content_ratings_proto_depIdxs = []int32{
	0, // 0: spotify.metadata.contentratings.v1.ContentRatings.tags:type_name -> spotify.metadata.contentratings.v1.ContentRatingTag
	0, // 1: spotify.metadata.contentratings.v1.ContentRatingTagWithMarkets.tag:type_name -> spotify.metadata.contentratings.v1.ContentRatingTag
	2, // 2: spotify.metadata.contentratings.v1.ContentRatingsWithMarket.rating_tags_with_markets:type_name -> spotify.metadata.contentratings.v1.ContentRatingTagWithMarkets
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_spotify_metadata_contentratings_v1_content_ratings_proto_init() }
func file_spotify_metadata_contentratings_v1_content_ratings_proto_init() {
	if File_spotify_metadata_contentratings_v1_content_ratings_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spotify_metadata_contentratings_v1_content_ratings_proto_rawDesc), len(file_spotify_metadata_contentratings_v1_content_ratings_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spotify_metadata_contentratings_v1_content_ratings_proto_goTypes,
		DependencyIndexes: file_spotify_metadata_contentratings_v1_content_ratings_proto_depIdxs,
		EnumInfos:         file_spotify_metadata_contentratings_v1_content_ratings_proto_enumTypes,
		MessageInfos:      file_spotify_metadata_contentratings_v1_content_ratings_proto_msgTypes,
	}.Build()
	File_spotify_metadata_contentratings_v1_content_ratings_proto = out.File
	file_spotify_metadata_contentratings_v1_content_ratings_proto_goTypes = nil
	file_spotify_metadata_contentratings_v1_content_ratings_proto_depIdxs = nil
}
