set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)

set(VCPKG_CMAKE_SYSTEM_NAME Linux)
set(VCPKG_BUILD_TYPE release)

if(PORT STREQUAL "dbus")
    set(VCPKG_CMAKE_CONFIGURE_OPTIONS -DDBUS_SESSION_SOCKET_DIR=/tmp)
endif()
