set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_ENV_PASSTHROUGH PATH)
set(VCPKG_CMAKE_SYSTEM_NAME MinGW)
set(VCPKG_BUILD_TYPE release)

# Match the Linux triplets: C decoder only. The C++ FLAC API is unused.
if(PORT STREQUAL "libflac")
    set(VCPKG_CMAKE_CONFIGURE_OPTIONS -DBUILD_CXXLIBS=OFF)
endif()
