// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: spotify/authentication.proto

package spotify

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthenticationType int32

const (
	AuthenticationType_AUTHENTICATION_USER_PASS                   AuthenticationType = 0
	AuthenticationType_AUTHENTICATION_STORED_SPOTIFY_CREDENTIALS  AuthenticationType = 1
	AuthenticationType_AUTHENTICATION_STORED_FACEBOOK_CREDENTIALS AuthenticationType = 2
	AuthenticationType_AUTHENTICATION_SPOTIFY_TOKEN               AuthenticationType = 3
	AuthenticationType_AUTHENTICATION_FACEBOOK_TOKEN              AuthenticationType = 4
)

// Enum value maps for AuthenticationType.
var (
	AuthenticationType_name = map[int32]string{
		0: "AUTHENTICATION_USER_PASS",
		1: "AUTHENTICATION_STORED_SPOTIFY_CREDENTIALS",
		2: "AUTHENTICATION_STORED_FACEBOOK_CREDENTIALS",
		3: "AUTHENTICATION_SPOTIFY_TOKEN",
		4: "AUTHENTICATION_FACEBOOK_TOKEN",
	}
	AuthenticationType_value = map[string]int32{
		"AUTHENTICATION_USER_PASS":                   0,
		"AUTHENTICATION_STORED_SPOTIFY_CREDENTIALS":  1,
		"AUTHENTICATION_STORED_FACEBOOK_CREDENTIALS": 2,
		"AUTHENTICATION_SPOTIFY_TOKEN":               3,
		"AUTHENTICATION_FACEBOOK_TOKEN":              4,
	}
)

func (x AuthenticationType) Enum() *AuthenticationType {
	p := new(AuthenticationType)
	*p = x
	return p
}

func (x AuthenticationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthenticationType) Descriptor() protoreflect.EnumDescriptor {
	return file_spotify_authentication_proto_enumTypes[0].Descriptor()
}

func (AuthenticationType) Type() protoreflect.EnumType {
	return &file_spotify_authentication_proto_enumTypes[0]
}

func (x AuthenticationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *AuthenticationType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = AuthenticationType(num)
	return nil
}

// Deprecated: Use AuthenticationType.Descriptor instead.
func (AuthenticationType) EnumDescriptor() ([]byte, []int) {
	return file_spotify_authentication_proto_rawDescGZIP(), []int{0}
}

type AccountCreation int32

const (
	AccountCreation_ACCOUNT_CREATION_ALWAYS_PROMPT AccountCreation = 1
	AccountCreation_ACCOUNT_CREATION_ALWAYS_CREATE AccountCreation = 3
)

// Enum value maps for AccountCreation.
var (
	AccountCreation_name = map[int32]string{
		1: "ACCOUNT_CREATION_ALWAYS_PROMPT",
		3: "ACCOUNT_CREATION_ALWAYS_CREATE",
	}
	AccountCreation_value = map[string]int32{
		"ACCOUNT_CREATION_ALWAYS_PROMPT": 1,
		"ACCOUNT_CREATION_ALWAYS_CREATE": 3,
	}
)

func (x AccountCreation) Enum() *AccountCreation {
	p := new(AccountCreation)
	*p = x
	return p
}

func (x AccountCreation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountCreation) Descriptor() protoreflect.EnumDescriptor {
	return file_spotify_authentication_proto_enumTypes[1].Descriptor()
}

func (AccountCreation) Type() protoreflect.EnumType {
	return &file_spotify_authentication_proto_enumTypes[1]
}

func (x AccountCreation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *AccountCreation) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = AccountCreation(num)
	return nil
}

// Deprecated: Use AccountCreation.Descriptor instead.
func (AccountCreation) EnumDescriptor() ([]byte, []int) {
	return file_spotify_authentication_proto_rawDescGZIP(), []int{1}
}

type CpuFamily int32

const (
	CpuFamily_CPU_UNKNOWN  CpuFamily = 0
	CpuFamily_CPU_X86      CpuFamily = 1
	CpuFamily_CPU_X86_64   CpuFamily = 2
	CpuFamily_CPU_PPC      CpuFamily = 3
	CpuFamily_CPU_PPC_64   CpuFamily = 4
	CpuFamily_CPU_ARM      CpuFamily = 5
	CpuFamily_CPU_IA64     CpuFamily = 6
	CpuFamily_CPU_SH       CpuFamily = 7
	CpuFamily_CPU_MIPS     CpuFamily = 8
	CpuFamily_CPU_BLACKFIN CpuFamily = 9
)

// Enum value maps for CpuFamily.
var (
	CpuFamily_name = map[int32]string{
		0: "CPU_UNKNOWN",
		1: "CPU_X86",
		2: "CPU_X86_64",
		3: "CPU_PPC",
		4: "CPU_PPC_64",
		5: "CPU_ARM",
		6: "CPU_IA64",
		7: "CPU_SH",
		8: "CPU_MIPS",
		9: "CPU_BLACKFIN",
	}
	CpuFamily_value = map[string]int32{
		"CPU_UNKNOWN":  0,
		"CPU_X86":      1,
		"CPU_X86_64":   2,
		"CPU_PPC":      3,
		"CPU_PPC_64":   4,
		"CPU_ARM":      5,
		"CPU_IA64":     6,
		"CPU_SH":       7,
		"CPU_MIPS":     8,
		"CPU_BLACKFIN": 9,
	}
)

func (x CpuFamily) Enum() *CpuFamily {
	p := new(CpuFamily)
	*p = x
	return p
}

func (x CpuFamily) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CpuFamily) Descriptor() protoreflect.EnumDescriptor {
	return file_spotify_authentication_proto_enumTypes[2].Descriptor()
}

func (CpuFamily) Type() protoreflect.EnumType {
	return &file_spotify_authentication_proto_enumTypes[2]
}

func (x CpuFamily) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *CpuFamily) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = CpuFamily(num)
	return nil
}

// Deprecated: Use CpuFamily.Descriptor instead.
func (CpuFamily) EnumDescriptor() ([]byte, []int) {
	return file_spotify_authentication_proto_rawDescGZIP(), []int{2}
}

type Brand int32

const (
	Brand_BRAND_UNBRANDED Brand = 0
	Brand_BRAND_INQ       Brand = 1
	Brand_BRAND_HTC       Brand = 2
	Brand_BRAND_NOKIA     Brand = 3
)

// Enum value maps for Brand.
var (
	Brand_name = map[int32]string{
		0: "BRAND_UNBRANDED",
		1: "BRAND_INQ",
		2: "BRAND_HTC",
		3: "BRAND_NOKIA",
	}
	Brand_value = map[string]int32{
		"BRAND_UNBRANDED": 0,
		"BRAND_INQ":       1,
		"BRAND_HTC":       2,
		"BRAND_NOKIA":     3,
	}
)

func (x Brand) Enum() *Brand {
	p := new(Brand)
	*p = x
	return p
}

func (x Brand) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Brand) Descriptor() protoreflect.EnumDescriptor {
	return file_spotify_authentication_proto_enumTypes[3].Descriptor()
}

func (Brand) Type() protoreflect.EnumType {
	return &file_spotify_authentication_proto_enumTypes[3]
}

func (x Brand) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Brand) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Brand(num)
	return nil
}

// Deprecated: Use Brand.Descriptor instead.
func (Brand) EnumDescriptor() ([]byte, []int) {
	return file_spotify_authentication_proto_rawDescGZIP(), []int{3}
}

type Os int32

const (
	Os_OS_UNKNOWN    Os = 0
	Os_OS_WINDOWS    Os = 1
	Os_OS_OSX        Os = 2
	Os_OS_IPHONE     Os = 3
	Os_OS_S60        Os = 4
	Os_OS_LINUX      Os = 5
	Os_OS_WINDOWS_CE Os = 6
	Os_OS_ANDROID    Os = 7
	Os_OS_PALM       Os = 8
	Os_OS_FREEBSD    Os = 9
	Os_OS_BLACKBERRY Os = 10
	Os_OS_SONOS      Os = 11
	Os_OS_LOGITECH   Os = 12
	Os_OS_WP7        Os = 13
	Os_OS_ONKYO      Os = 14
	Os_OS_PHILIPS    Os = 15
	Os_OS_WD         Os = 16
	Os_OS_VOLVO      Os = 17
	Os_OS_TIVO       Os = 18
	Os_OS_AWOX       Os = 19
	Os_OS_MEEGO      Os = 20
	Os_OS_QNXNTO     Os = 21
	Os_OS_BCO        Os = 22
)

// Enum value maps for Os.
var (
	Os_name = map[int32]string{
		0:  "OS_UNKNOWN",
		1:  "OS_WINDOWS",
		2:  "OS_OSX",
		3:  "OS_IPHONE",
		4:  "OS_S60",
		5:  "OS_LINUX",
		6:  "OS_WINDOWS_CE",
		7:  "OS_ANDROID",
		8:  "OS_PALM",
		9:  "OS_FREEBSD",
		10: "OS_BLACKBERRY",
		11: "OS_SONOS",
		12: "OS_LOGITECH",
		13: "OS_WP7",
		14: "OS_ONKYO",
		15: "OS_PHILIPS",
		16: "OS_WD",
		17: "OS_VOLVO",
		18: "OS_TIVO",
		19: "OS_AWOX",
		20: "OS_MEEGO",
		21: "OS_QNXNTO",
		22: "OS_BCO",
	}
	Os_value = map[string]int32{
		"OS_UNKNOWN":    0,
		"OS_WINDOWS":    1,
		"OS_OSX":        2,
		"OS_IPHONE":     3,
		"OS_S60":        4,
		"OS_LINUX":      5,
		"OS_WINDOWS_CE": 6,
		"OS_ANDROID":    7,
		"OS_PALM":       8,
		"OS_FREEBSD":    9,
		"OS_BLACKBERRY": 10,
		"OS_SONOS":      11,
		"OS_LOGITECH":   12,
		"OS_WP7":        13,
		"OS_ONKYO":      14,
		"OS_PHILIPS":    15,
		"OS_WD":         16,
		"OS_VOLVO":      17,
		"OS_TIVO":       18,
		"OS_AWOX":       19,
		"OS_MEEGO":      20,
		"OS_QNXNTO":     21,
		"OS_BCO":        22,
	}
)

func (x Os) Enum() *Os {
	p := new(Os)
	*p = x
	return p
}

func (x Os) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Os) Descriptor() protoreflect.EnumDescriptor {
	return file_spotify_authentication_proto_enumTypes[4].Descriptor()
}

func (Os) Type() protoreflect.EnumType {
	return &file_spotify_authentication_proto_enumTypes[4]
}

func (x Os) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Os) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Os(num)
	return nil
}

// Deprecated: Use Os.Descriptor instead.
func (Os) EnumDescriptor() ([]byte, []int) {
	return file_spotify_authentication_proto_rawDescGZIP(), []int{4}
}

type AccountType int32

const (
	AccountType_Spotify  AccountType = 0
	AccountType_Facebook AccountType = 1
)

// Enum value maps for AccountType.
var (
	AccountType_name = map[int32]string{
		0: "Spotify",
		1: "Facebook",
	}
	AccountType_value = map[string]int32{
		"Spotify":  0,
		"Facebook": 1,
	}
)

func (x AccountType) Enum() *AccountType {
	p := new(AccountType)
	*p = x
	return p
}

func (x AccountType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountType) Descriptor() protoreflect.EnumDescriptor {
	return file_spotify_authentication_proto_enumTypes[5].Descriptor()
}

func (AccountType) Type() protoreflect.EnumType {
	return &file_spotify_authentication_proto_enumTypes[5]
}

func (x AccountType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *AccountType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = AccountType(num)
	return nil
}

// Deprecated: Use AccountType.Descriptor instead.
func (AccountType) EnumDescriptor() ([]byte, []int) {
	return file_spotify_authentication_proto_rawDescGZIP(), []int{5}
}

type ClientResponseEncrypted struct {
	state               protoimpl.MessageState    `protogen:"open.v1"`
	LoginCredentials    *LoginCredentials         `protobuf:"bytes,10,req,name=login_credentials,json=loginCredentials" json:"login_credentials,omitempty"`
	AccountCreation     *AccountCreation          `protobuf:"varint,20,opt,name=account_creation,json=accountCreation,enum=spotify.AccountCreation" json:"account_creation,omitempty"`
	FingerprintResponse *FingerprintResponseUnion `protobuf:"bytes,30,opt,name=fingerprint_response,json=fingerprintResponse" json:"fingerprint_response,omitempty"`
	PeerTicket          *PeerTicketUnion          `protobuf:"bytes,40,opt,name=peer_ticket,json=peerTicket" json:"peer_ticket,omitempty"`
	SystemInfo          *SystemInfo               `protobuf:"bytes,50,req,name=system_info,json=systemInfo" json:"system_info,omitempty"`
	PlatformModel       *string                   `protobuf:"bytes,60,opt,name=platform_model,json=platformModel" json:"platform_model,omitempty"`
	VersionString       *string                   `protobuf:"bytes,70,opt,name=version_string,json=versionString" json:"version_string,omitempty"`
	Appkey              *LibspotifyAppKey         `protobuf:"bytes,80,opt,name=appkey" json:"appkey,omitempty"`
	ClientInfo          *ClientInfo               `protobuf:"bytes,90,opt,name=client_info,json=clientInfo" json:"client_info,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ClientResponseEncrypted) Reset() {
	*x = ClientResponseEncrypted{}
	mi := &file_spotify_authentication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientResponseEncrypted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientResponseEncrypted) ProtoMessage() {}

func (x *ClientResponseEncrypted) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_authentication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientResponseEncrypted.ProtoReflect.Descriptor instead.
func (*ClientResponseEncrypted) Descriptor() ([]byte, []int) {
	return file_spotify_authentication_proto_rawDescGZIP(), []int{0}
}

func (x *ClientResponseEncrypted) GetLoginCredentials() *LoginCredentials {
	if x != nil {
		return x.LoginCredentials
	}
	return nil
}

func (x *ClientResponseEncrypted) GetAccountCreation() AccountCreation {
	if x != nil && x.AccountCreation != nil {
		return *x.AccountCreation
	}
	return AccountCreation_ACCOUNT_CREATION_ALWAYS_PROMPT
}

func (x *ClientResponseEncrypted) GetFingerprintResponse() *FingerprintResponseUnion {
	if x != nil {
		return x.FingerprintResponse
	}
	return nil
}

func (x *ClientResponseEncrypted) GetPeerTicket() *PeerTicketUnion {
	if x != nil {
		return x.PeerTicket
	}
	return nil
}

func (x *ClientResponseEncrypted) GetSystemInfo() *SystemInfo {
	if x != nil {
		return x.SystemInfo
	}
	return nil
}

func (x *ClientResponseEncrypted) GetPlatformModel() string {
	if x != nil && x.PlatformModel != nil {
		return *x.PlatformModel
	}
	return ""
}

func (x *ClientResponseEncrypted) GetVersionString() string {
	if x != nil && x.VersionString != nil {
		return *x.VersionString
	}
	return ""
}

func (x *ClientResponseEncrypted) GetAppkey() *LibspotifyAppKey {
	if x != nil {
		return x.Appkey
	}
	return nil
}

func (x *ClientResponseEncrypted) GetClientInfo() *ClientInfo {
	if x != nil {
		return x.ClientInfo
	}
	return nil
}

type LoginCredentials struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      *string                `protobuf:"bytes,10,opt,name=username" json:"username,omitempty"`
	Typ           *AuthenticationType    `protobuf:"varint,20,req,name=typ,enum=spotify.AuthenticationType" json:"typ,omitempty"`
	AuthData      []byte                 `protobuf:"bytes,30,opt,name=auth_data,json=authData" json:"auth_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginCredentials) Reset() {
	*x = LoginCredentials{}
	mi := &file_spotify_authentication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginCredentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginCredentials) ProtoMessage() {}

func (x *LoginCredentials) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_authentication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginCredentials.ProtoReflect.Descriptor instead.
func (*LoginCredentials) Descriptor() ([]byte, []int) {
	return file_spotify_authentication_proto_rawDescGZIP(), []int{1}
}

func (x *LoginCredentials) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *LoginCredentials) GetTyp() AuthenticationType {
	if x != nil && x.Typ != nil {
		return *x.Typ
	}
	return AuthenticationType_AUTHENTICATION_USER_PASS
}

func (x *LoginCredentials) GetAuthData() []byte {
	if x != nil {
		return x.AuthData
	}
	return nil
}

type FingerprintResponseUnion struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Grain         *FingerprintGrainResponse      `protobuf:"bytes,10,opt,name=grain" json:"grain,omitempty"`
	HmacRipemd    *FingerprintHmacRipemdResponse `protobuf:"bytes,20,opt,name=hmac_ripemd,json=hmacRipemd" json:"hmac_ripemd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FingerprintResponseUnion) Reset() {
	*x = FingerprintResponseUnion{}
	mi := &file_spotify_authentication_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FingerprintResponseUnion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FingerprintResponseUnion) ProtoMessage() {}

func (x *FingerprintResponseUnion) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_authentication_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FingerprintResponseUnion.ProtoReflect.Descriptor instead.
func (*FingerprintResponseUnion) Descriptor() ([]byte, []int) {
	return file_spotify_authentication_proto_rawDescGZIP(), []int{2}
}

func (x *FingerprintResponseUnion) GetGrain() *FingerprintGrainResponse {
	if x != nil {
		return x.Grain
	}
	return nil
}

func (x *FingerprintResponseUnion) GetHmacRipemd() *FingerprintHmacRipemdResponse {
	if x != nil {
		return x.HmacRipemd
	}
	return nil
}

type FingerprintGrainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EncryptedKey  []byte                 `protobuf:"bytes,10,req,name=encrypted_key,json=encryptedKey" json:"encrypted_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FingerprintGrainResponse) Reset() {
	*x = FingerprintGrainResponse{}
	mi := &file_spotify_authentication_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FingerprintGrainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FingerprintGrainResponse) ProtoMessage() {}

func (x *FingerprintGrainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_authentication_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FingerprintGrainResponse.ProtoReflect.Descriptor instead.
func (*FingerprintGrainResponse) Descriptor() ([]byte, []int) {
	return file_spotify_authentication_proto_rawDescGZIP(), []int{3}
}

func (x *FingerprintGrainResponse) GetEncryptedKey() []byte {
	if x != nil {
		return x.EncryptedKey
	}
	return nil
}

type FingerprintHmacRipemdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hmac          []byte                 `protobuf:"bytes,10,req,name=hmac" json:"hmac,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FingerprintHmacRipemdResponse) Reset() {
	*x = FingerprintHmacRipemdResponse{}
	mi := &file_spotify_authentication_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FingerprintHmacRipemdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FingerprintHmacRipemdResponse) ProtoMessage() {}

func (x *FingerprintHmacRipemdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_authentication_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FingerprintHmacRipemdResponse.ProtoReflect.Descriptor instead.
func (*FingerprintHmacRipemdResponse) Descriptor() ([]byte, []int) {
	return file_spotify_authentication_proto_rawDescGZIP(), []int{4}
}

func (x *FingerprintHmacRipemdResponse) GetHmac() []byte {
	if x != nil {
		return x.Hmac
	}
	return nil
}

type PeerTicketUnion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     *PeerTicketPublicKey   `protobuf:"bytes,10,opt,name=public_key,json=publicKey" json:"public_key,omitempty"`
	OldTicket     *PeerTicketOld         `protobuf:"bytes,20,opt,name=old_ticket,json=oldTicket" json:"old_ticket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerTicketUnion) Reset() {
	*x = PeerTicketUnion{}
	mi := &file_spotify_authentication_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerTicketUnion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerTicketUnion) ProtoMessage() {}

func (x *PeerTicketUnion) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_authentication_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerTicketUnion.ProtoReflect.Descriptor instead.
func (*PeerTicketUnion) Descriptor() ([]byte, []int) {
	return file_spotify_authentication_proto_rawDescGZIP(), []int{5}
}

func (x *PeerTicketUnion) GetPublicKey() *PeerTicketPublicKey {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *PeerTicketUnion) GetOldTicket() *PeerTicketOld {
	if x != nil {
		return x.OldTicket
	}
	return nil
}

type PeerTicketPublicKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     []byte                 `protobuf:"bytes,10,req,name=public_key,json=publicKey" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerTicketPublicKey) Reset() {
	*x = PeerTicketPublicKey{}
	mi := &file_spotify_authentication_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerTicketPublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerTicketPublicKey) ProtoMessage() {}

func (x *PeerTicketPublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_authentication_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerTicketPublicKey.ProtoReflect.Descriptor instead.
func (*PeerTicketPublicKey) Descriptor() ([]byte, []int) {
	return file_spotify_authentication_proto_rawDescGZIP(), []int{6}
}

func (x *PeerTicketPublicKey) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type PeerTicketOld struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PeerTicket          []byte                 `protobuf:"bytes,10,req,name=peer_ticket,json=peerTicket" json:"peer_ticket,omitempty"`
	PeerTicketSignature []byte                 `protobuf:"bytes,20,req,name=peer_ticket_signature,json=peerTicketSignature" json:"peer_ticket_signature,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PeerTicketOld) Reset() {
	*x = PeerTicketOld{}
	mi := &file_spotify_authentication_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerTicketOld) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerTicketOld) ProtoMessage() {}

func (x *PeerTicketOld) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_authentication_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerTicketOld.ProtoReflect.Descriptor instead.
func (*PeerTicketOld) Descriptor() ([]byte, []int) {
	return file_spotify_authentication_proto_rawDescGZIP(), []int{7}
}

func (x *PeerTicketOld) GetPeerTicket() []byte {
	if x != nil {
		return x.PeerTicket
	}
	return nil
}

func (x *PeerTicketOld) GetPeerTicketSignature() []byte {
	if x != nil {
		return x.PeerTicketSignature
	}
	return nil
}

type SystemInfo struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	CpuFamily               *CpuFamily             `protobuf:"varint,10,req,name=cpu_family,json=cpuFamily,enum=spotify.CpuFamily" json:"cpu_family,omitempty"`
	CpuSubtype              *uint32                `protobuf:"varint,20,opt,name=cpu_subtype,json=cpuSubtype" json:"cpu_subtype,omitempty"`
	CpuExt                  *uint32                `protobuf:"varint,30,opt,name=cpu_ext,json=cpuExt" json:"cpu_ext,omitempty"`
	Brand                   *Brand                 `protobuf:"varint,40,opt,name=brand,enum=spotify.Brand" json:"brand,omitempty"`
	BrandFlags              *uint32                `protobuf:"varint,50,opt,name=brand_flags,json=brandFlags" json:"brand_flags,omitempty"`
	Os                      *Os                    `protobuf:"varint,60,req,name=os,enum=spotify.Os" json:"os,omitempty"`
	OsVersion               *uint32                `protobuf:"varint,70,opt,name=os_version,json=osVersion" json:"os_version,omitempty"`
	OsExt                   *uint32                `protobuf:"varint,80,opt,name=os_ext,json=osExt" json:"os_ext,omitempty"`
	SystemInformationString *string                `protobuf:"bytes,90,opt,name=system_information_string,json=systemInformationString" json:"system_information_string,omitempty"`
	DeviceId                *string                `protobuf:"bytes,100,opt,name=device_id,json=deviceId" json:"device_id,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *SystemInfo) Reset() {
	*x = SystemInfo{}
	mi := &file_spotify_authentication_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo) ProtoMessage() {}

func (x *SystemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_authentication_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo.ProtoReflect.Descriptor instead.
func (*SystemInfo) Descriptor() ([]byte, []int) {
	return file_spotify_authentication_proto_rawDescGZIP(), []int{8}
}

func (x *SystemInfo) GetCpuFamily() CpuFamily {
	if x != nil && x.CpuFamily != nil {
		return *x.CpuFamily
	}
	return CpuFamily_CPU_UNKNOWN
}

func (x *SystemInfo) GetCpuSubtype() uint32 {
	if x != nil && x.CpuSubtype != nil {
		return *x.CpuSubtype
	}
	return 0
}

func (x *SystemInfo) GetCpuExt() uint32 {
	if x != nil && x.CpuExt != nil {
		return *x.CpuExt
	}
	return 0
}

func (x *SystemInfo) GetBrand() Brand {
	if x != nil && x.Brand != nil {
		return *x.Brand
	}
	return Brand_BRAND_UNBRANDED
}

func (x *SystemInfo) GetBrandFlags() uint32 {
	if x != nil && x.BrandFlags != nil {
		return *x.BrandFlags
	}
	return 0
}

func (x *SystemInfo) GetOs() Os {
	if x != nil && x.Os != nil {
		return *x.Os
	}
	return Os_OS_UNKNOWN
}

func (x *SystemInfo) GetOsVersion() uint32 {
	if x != nil && x.OsVersion != nil {
		return *x.OsVersion
	}
	return 0
}

func (x *SystemInfo) GetOsExt() uint32 {
	if x != nil && x.OsExt != nil {
		return *x.OsExt
	}
	return 0
}

func (x *SystemInfo) GetSystemInformationString() string {
	if x != nil && x.SystemInformationString != nil {
		return *x.SystemInformationString
	}
	return ""
}

func (x *SystemInfo) GetDeviceId() string {
	if x != nil && x.DeviceId != nil {
		return *x.DeviceId
	}
	return ""
}

type LibspotifyAppKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       *uint32                `protobuf:"varint,1,req,name=version" json:"version,omitempty"`
	Devkey        []byte                 `protobuf:"bytes,2,req,name=devkey" json:"devkey,omitempty"`
	Signature     []byte                 `protobuf:"bytes,3,req,name=signature" json:"signature,omitempty"`
	Useragent     *string                `protobuf:"bytes,4,req,name=useragent" json:"useragent,omitempty"`
	CallbackHash  []byte                 `protobuf:"bytes,5,req,name=callback_hash,json=callbackHash" json:"callback_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LibspotifyAppKey) Reset() {
	*x = LibspotifyAppKey{}
	mi := &file_spotify_authentication_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LibspotifyAppKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LibspotifyAppKey) ProtoMessage() {}

func (x *LibspotifyAppKey) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_authentication_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LibspotifyAppKey.ProtoReflect.Descriptor instead.
func (*LibspotifyAppKey) Descriptor() ([]byte, []int) {
	return file_spotify_authentication_proto_rawDescGZIP(), []int{9}
}

func (x *LibspotifyAppKey) GetVersion() uint32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *LibspotifyAppKey) GetDevkey() []byte {
	if x != nil {
		return x.Devkey
	}
	return nil
}

func (x *LibspotifyAppKey) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *LibspotifyAppKey) GetUseragent() string {
	if x != nil && x.Useragent != nil {
		return *x.Useragent
	}
	return ""
}

func (x *LibspotifyAppKey) GetCallbackHash() []byte {
	if x != nil {
		return x.CallbackHash
	}
	return nil
}

type ClientInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limited       *bool                  `protobuf:"varint,1,opt,name=limited" json:"limited,omitempty"`
	Fb            *ClientInfoFacebook    `protobuf:"bytes,2,opt,name=fb" json:"fb,omitempty"`
	Language      *string                `protobuf:"bytes,3,opt,name=language" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientInfo) Reset() {
	*x = ClientInfo{}
	mi := &file_spotify_authentication_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientInfo) ProtoMessage() {}

func (x *ClientInfo) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_authentication_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientInfo.ProtoReflect.Descriptor instead.
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return file_spotify_authentication_proto_rawDescGZIP(), []int{10}
}

func (x *ClientInfo) GetLimited() bool {
	if x != nil && x.Limited != nil {
		return *x.Limited
	}
	return false
}

func (x *ClientInfo) GetFb() *ClientInfoFacebook {
	if x != nil {
		return x.Fb
	}
	return nil
}

func (x *ClientInfo) GetLanguage() string {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return ""
}

type ClientInfoFacebook struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineId     *string                `protobuf:"bytes,1,opt,name=machine_id,json=machineId" json:"machine_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientInfoFacebook) Reset() {
	*x = ClientInfoFacebook{}
	mi := &file_spotify_authentication_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientInfoFacebook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientInfoFacebook) ProtoMessage() {}

func (x *ClientInfoFacebook) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_authentication_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientInfoFacebook.ProtoReflect.Descriptor instead.
func (*ClientInfoFacebook) Descriptor() ([]byte, []int) {
	return file_spotify_authentication_proto_rawDescGZIP(), []int{11}
}

func (x *ClientInfoFacebook) GetMachineId() string {
	if x != nil && x.MachineId != nil {
		return *x.MachineId
	}
	return ""
}

type APWelcome struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	CanonicalUsername           *string                `protobuf:"bytes,10,req,name=canonical_username,json=canonicalUsername" json:"canonical_username,omitempty"`
	AccountTypeLoggedIn         *AccountType           `protobuf:"varint,20,req,name=account_type_logged_in,json=accountTypeLoggedIn,enum=spotify.AccountType" json:"account_type_logged_in,omitempty"`
	CredentialsTypeLoggedIn     *AccountType           `protobuf:"varint,25,req,name=credentials_type_logged_in,json=credentialsTypeLoggedIn,enum=spotify.AccountType" json:"credentials_type_logged_in,omitempty"`
	ReusableAuthCredentialsType *AuthenticationType    `protobuf:"varint,30,req,name=reusable_auth_credentials_type,json=reusableAuthCredentialsType,enum=spotify.AuthenticationType" json:"reusable_auth_credentials_type,omitempty"`
	ReusableAuthCredentials     []byte                 `protobuf:"bytes,40,req,name=reusable_auth_credentials,json=reusableAuthCredentials" json:"reusable_auth_credentials,omitempty"`
	LfsSecret                   []byte                 `protobuf:"bytes,50,opt,name=lfs_secret,json=lfsSecret" json:"lfs_secret,omitempty"`
	AccountInfo                 *AccountInfo           `protobuf:"bytes,60,opt,name=account_info,json=accountInfo" json:"account_info,omitempty"`
	Fb                          *AccountInfoFacebook   `protobuf:"bytes,70,opt,name=fb" json:"fb,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *APWelcome) Reset() {
	*x = APWelcome{}
	mi := &file_spotify_authentication_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APWelcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APWelcome) ProtoMessage() {}

func (x *APWelcome) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_authentication_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APWelcome.ProtoReflect.Descriptor instead.
func (*APWelcome) Descriptor() ([]byte, []int) {
	return file_spotify_authentication_proto_rawDescGZIP(), []int{12}
}

func (x *APWelcome) GetCanonicalUsername() string {
	if x != nil && x.CanonicalUsername != nil {
		return *x.CanonicalUsername
	}
	return ""
}

func (x *APWelcome) GetAccountTypeLoggedIn() AccountType {
	if x != nil && x.AccountTypeLoggedIn != nil {
		return *x.AccountTypeLoggedIn
	}
	return AccountType_Spotify
}

func (x *APWelcome) GetCredentialsTypeLoggedIn() AccountType {
	if x != nil && x.CredentialsTypeLoggedIn != nil {
		return *x.CredentialsTypeLoggedIn
	}
	return AccountType_Spotify
}

func (x *APWelcome) GetReusableAuthCredentialsType() AuthenticationType {
	if x != nil && x.ReusableAuthCredentialsType != nil {
		return *x.ReusableAuthCredentialsType
	}
	return AuthenticationType_AUTHENTICATION_USER_PASS
}

func (x *APWelcome) GetReusableAuthCredentials() []byte {
	if x != nil {
		return x.ReusableAuthCredentials
	}
	return nil
}

func (x *APWelcome) GetLfsSecret() []byte {
	if x != nil {
		return x.LfsSecret
	}
	return nil
}

func (x *APWelcome) GetAccountInfo() *AccountInfo {
	if x != nil {
		return x.AccountInfo
	}
	return nil
}

func (x *APWelcome) GetFb() *AccountInfoFacebook {
	if x != nil {
		return x.Fb
	}
	return nil
}

type AccountInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spotify       *AccountInfoSpotify    `protobuf:"bytes,1,opt,name=spotify" json:"spotify,omitempty"`
	Facebook      *AccountInfoFacebook   `protobuf:"bytes,2,opt,name=facebook" json:"facebook,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountInfo) Reset() {
	*x = AccountInfo{}
	mi := &file_spotify_authentication_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountInfo) ProtoMessage() {}

func (x *AccountInfo) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_authentication_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountInfo.ProtoReflect.Descriptor instead.
func (*AccountInfo) Descriptor() ([]byte, []int) {
	return file_spotify_authentication_proto_rawDescGZIP(), []int{13}
}

func (x *AccountInfo) GetSpotify() *AccountInfoSpotify {
	if x != nil {
		return x.Spotify
	}
	return nil
}

func (x *AccountInfo) GetFacebook() *AccountInfoFacebook {
	if x != nil {
		return x.Facebook
	}
	return nil
}

type AccountInfoSpotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountInfoSpotify) Reset() {
	*x = AccountInfoSpotify{}
	mi := &file_spotify_authentication_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountInfoSpotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountInfoSpotify) ProtoMessage() {}

func (x *AccountInfoSpotify) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_authentication_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountInfoSpotify.ProtoReflect.Descriptor instead.
func (*AccountInfoSpotify) Descriptor() ([]byte, []int) {
	return file_spotify_authentication_proto_rawDescGZIP(), []int{14}
}

type AccountInfoFacebook struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   *string                `protobuf:"bytes,1,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	MachineId     *string                `protobuf:"bytes,2,opt,name=machine_id,json=machineId" json:"machine_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountInfoFacebook) Reset() {
	*x = AccountInfoFacebook{}
	mi := &file_spotify_authentication_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountInfoFacebook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountInfoFacebook) ProtoMessage() {}

func (x *AccountInfoFacebook) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_authentication_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountInfoFacebook.ProtoReflect.Descriptor instead.
func (*AccountInfoFacebook) Descriptor() ([]byte, []int) {
	return file_spotify_authentication_proto_rawDescGZIP(), []int{15}
}

func (x *AccountInfoFacebook) GetAccessToken() string {
	if x != nil && x.AccessToken != nil {
		return *x.AccessToken
	}
	return ""
}

func (x *AccountInfoFacebook) GetMachineId() string {
	if x != nil && x.MachineId != nil {
		return *x.MachineId
	}
	return ""
}

var File_spotify_authentication_proto protoreflect.FileDescriptor

const file_spotify_authentication_proto_rawDesc = "" +
	"\n" +
	"\x1cspotify/authentication.proto\x12\aspotify\"\xa4\x04\n" +
	"\x17ClientResponseEncrypted\x12F\n" +
	"\x11login_credentials\x18\n" +
	" \x02(\v2\x19.spotify.LoginCredentialsR\x10loginCredentials\x12C\n" +
	"\x10account_creation\x18\x14 \x01(\x0e2\x18.spotify.AccountCreationR\x0faccountCreation\x12T\n" +
	"\x14fingerprint_response\x18\x1e \x01(\v2!.spotify.FingerprintResponseUnionR\x13fingerprintResponse\x129\n" +
	"\vpeer_ticket\x18( \x01(\v2\x18.spotify.PeerTicketUnionR\n" +
	"peerTicket\x124\n" +
	"\vsystem_info\x182 \x02(\v2\x13.spotify.SystemInfoR\n" +
	"systemInfo\x12%\n" +
	"\x0eplatform_model\x18< \x01(\tR\rplatformModel\x12%\n" +
	"\x0eversion_string\x18F \x01(\tR\rversionString\x121\n" +
	"\x06appkey\x18P \x01(\v2\x19.spotify.LibspotifyAppKeyR\x06appkey\x124\n" +
	"\vclient_info\x18Z \x01(\v2\x13.spotify.ClientInfoR\n" +
	"clientInfo\"z\n" +
	"\x10LoginCredentials\x12\x1a\n" +
	"\busername\x18\n" +
	" \x01(\tR\busername\x12-\n" +
	"\x03typ\x18\x14 \x02(\x0e2\x1b.spotify.AuthenticationTypeR\x03typ\x12\x1b\n" +
	"\tauth_data\x18\x1e \x01(\fR\bauthData\"\x9c\x01\n" +
	"\x18FingerprintResponseUnion\x127\n" +
	"\x05grain\x18\n" +
	" \x01(\v2!.spotify.FingerprintGrainResponseR\x05grain\x12G\n" +
	"\vhmac_ripemd\x18\x14 \x01(\v2&.spotify.FingerprintHmacRipemdResponseR\n" +
	"hmacRipemd\"?\n" +
	"\x18FingerprintGrainResponse\x12#\n" +
	"\rencrypted_key\x18\n" +
	" \x02(\fR\fencryptedKey\"3\n" +
	"\x1dFingerprintHmacRipemdResponse\x12\x12\n" +
	"\x04hmac\x18\n" +
	" \x02(\fR\x04hmac\"\x85\x01\n" +
	"\x0fPeerTicketUnion\x12;\n" +
	"\n" +
	"public_key\x18\n" +
	" \x01(\v2\x1c.spotify.PeerTicketPublicKeyR\tpublicKey\x125\n" +
	"\n" +
	"old_ticket\x18\x14 \x01(\v2\x16.spotify.PeerTicketOldR\toldTicket\"4\n" +
	"\x13PeerTicketPublicKey\x12\x1d\n" +
	"\n" +
	"public_key\x18\n" +
	" \x02(\fR\tpublicKey\"d\n" +
	"\rPeerTicketOld\x12\x1f\n" +
	"\vpeer_ticket\x18\n" +
	" \x02(\fR\n" +
	"peerTicket\x122\n" +
	"\x15peer_ticket_signature\x18\x14 \x02(\fR\x13peerTicketSignature\"\xec\x02\n" +
	"\n" +
	"SystemInfo\x121\n" +
	"\n" +
	"cpu_family\x18\n" +
	" \x02(\x0e2\x12.spotify.CpuFamilyR\tcpuFamily\x12\x1f\n" +
	"\vcpu_subtype\x18\x14 \x01(\rR\n" +
	"cpuSubtype\x12\x17\n" +
	"\acpu_ext\x18\x1e \x01(\rR\x06cpuExt\x12$\n" +
	"\x05brand\x18( \x01(\x0e2\x0e.spotify.BrandR\x05brand\x12\x1f\n" +
	"\vbrand_flags\x182 \x01(\rR\n" +
	"brandFlags\x12\x1b\n" +
	"\x02os\x18< \x02(\x0e2\v.spotify.OsR\x02os\x12\x1d\n" +
	"\n" +
	"os_version\x18F \x01(\rR\tosVersion\x12\x15\n" +
	"\x06os_ext\x18P \x01(\rR\x05osExt\x12:\n" +
	"\x19system_information_string\x18Z \x01(\tR\x17systemInformationString\x12\x1b\n" +
	"\tdevice_id\x18d \x01(\tR\bdeviceId\"\xa5\x01\n" +
	"\x10LibspotifyAppKey\x12\x18\n" +
	"\aversion\x18\x01 \x02(\rR\aversion\x12\x16\n" +
	"\x06devkey\x18\x02 \x02(\fR\x06devkey\x12\x1c\n" +
	"\tsignature\x18\x03 \x02(\fR\tsignature\x12\x1c\n" +
	"\tuseragent\x18\x04 \x02(\tR\tuseragent\x12#\n" +
	"\rcallback_hash\x18\x05 \x02(\fR\fcallbackHash\"o\n" +
	"\n" +
	"ClientInfo\x12\x18\n" +
	"\alimited\x18\x01 \x01(\bR\alimited\x12+\n" +
	"\x02fb\x18\x02 \x01(\v2\x1b.spotify.ClientInfoFacebookR\x02fb\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\"3\n" +
	"\x12ClientInfoFacebook\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\"\xfc\x03\n" +
	"\tAPWelcome\x12-\n" +
	"\x12canonical_username\x18\n" +
	" \x02(\tR\x11canonicalUsername\x12I\n" +
	"\x16account_type_logged_in\x18\x14 \x02(\x0e2\x14.spotify.AccountTypeR\x13accountTypeLoggedIn\x12Q\n" +
	"\x1acredentials_type_logged_in\x18\x19 \x02(\x0e2\x14.spotify.AccountTypeR\x17credentialsTypeLoggedIn\x12`\n" +
	"\x1ereusable_auth_credentials_type\x18\x1e \x02(\x0e2\x1b.spotify.AuthenticationTypeR\x1breusableAuthCredentialsType\x12:\n" +
	"\x19reusable_auth_credentials\x18( \x02(\fR\x17reusableAuthCredentials\x12\x1d\n" +
	"\n" +
	"lfs_secret\x182 \x01(\fR\tlfsSecret\x127\n" +
	"\faccount_info\x18< \x01(\v2\x14.spotify.AccountInfoR\vaccountInfo\x12,\n" +
	"\x02fb\x18F \x01(\v2\x1c.spotify.AccountInfoFacebookR\x02fb\"~\n" +
	"\vAccountInfo\x125\n" +
	"\aspotify\x18\x01 \x01(\v2\x1b.spotify.AccountInfoSpotifyR\aspotify\x128\n" +
	"\bfacebook\x18\x02 \x01(\v2\x1c.spotify.AccountInfoFacebookR\bfacebook\"\x14\n" +
	"\x12AccountInfoSpotify\"W\n" +
	"\x13AccountInfoFacebook\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x02 \x01(\tR\tmachineId*\xd6\x01\n" +
	"\x12AuthenticationType\x12\x1c\n" +
	"\x18AUTHENTICATION_USER_PASS\x10\x00\x12-\n" +
	")AUTHENTICATION_STORED_SPOTIFY_CREDENTIALS\x10\x01\x12.\n" +
	"*AUTHENTICATION_STORED_FACEBOOK_CREDENTIALS\x10\x02\x12 \n" +
	"\x1cAUTHENTICATION_SPOTIFY_TOKEN\x10\x03\x12!\n" +
	"\x1dAUTHENTICATION_FACEBOOK_TOKEN\x10\x04*Y\n" +
	"\x0fAccountCreation\x12\"\n" +
	"\x1eACCOUNT_CREATION_ALWAYS_PROMPT\x10\x01\x12\"\n" +
	"\x1eACCOUNT_CREATION_ALWAYS_CREATE\x10\x03*\x9d\x01\n" +
	"\tCpuFamily\x12\x0f\n" +
	"\vCPU_UNKNOWN\x10\x00\x12\v\n" +
	"\aCPU_X86\x10\x01\x12\x0e\n" +
	"\n" +
	"CPU_X86_64\x10\x02\x12\v\n" +
	"\aCPU_PPC\x10\x03\x12\x0e\n" +
	"\n" +
	"CPU_PPC_64\x10\x04\x12\v\n" +
	"\aCPU_ARM\x10\x05\x12\f\n" +
	"\bCPU_IA64\x10\x06\x12\n" +
	"\n" +
	"\x06CPU_SH\x10\a\x12\f\n" +
	"\bCPU_MIPS\x10\b\x12\x10\n" +
	"\fCPU_BLACKFIN\x10\t*K\n" +
	"\x05Brand\x12\x13\n" +
	"\x0fBRAND_UNBRANDED\x10\x00\x12\r\n" +
	"\tBRAND_INQ\x10\x01\x12\r\n" +
	"\tBRAND_HTC\x10\x02\x12\x0f\n" +
	"\vBRAND_NOKIA\x10\x03*\xd1\x02\n" +
	"\x02Os\x12\x0e\n" +
	"\n" +
	"OS_UNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"OS_WINDOWS\x10\x01\x12\n" +
	"\n" +
	"\x06OS_OSX\x10\x02\x12\r\n" +
	"\tOS_IPHONE\x10\x03\x12\n" +
	"\n" +
	"\x06OS_S60\x10\x04\x12\f\n" +
	"\bOS_LINUX\x10\x05\x12\x11\n" +
	"\rOS_WINDOWS_CE\x10\x06\x12\x0e\n" +
	"\n" +
	"OS_ANDROID\x10\a\x12\v\n" +
	"\aOS_PALM\x10\b\x12\x0e\n" +
	"\n" +
	"OS_FREEBSD\x10\t\x12\x11\n" +
	"\rOS_BLACKBERRY\x10\n" +
	"\x12\f\n" +
	"\bOS_SONOS\x10\v\x12\x0f\n" +
	"\vOS_LOGITECH\x10\f\x12\n" +
	"\n" +
	"\x06OS_WP7\x10\r\x12\f\n" +
	"\bOS_ONKYO\x10\x0e\x12\x0e\n" +
	"\n" +
	"OS_PHILIPS\x10\x0f\x12\t\n" +
	"\x05OS_WD\x10\x10\x12\f\n" +
	"\bOS_VOLVO\x10\x11\x12\v\n" +
	"\aOS_TIVO\x10\x12\x12\v\n" +
	"\aOS_AWOX\x10\x13\x12\f\n" +
	"\bOS_MEEGO\x10\x14\x12\r\n" +
	"\tOS_QNXNTO\x10\x15\x12\n" +
	"\n" +
	"\x06OS_BCO\x10\x16*(\n" +
	"\vAccountType\x12\v\n" +
	"\aSpotify\x10\x00\x12\f\n" +
	"\bFacebook\x10\x01B\x8f\x01\n" +
	"\vcom.spotifyB\x13AuthenticationProtoP\x01Z/github.com/devgianlu/go-librespot/proto/spotify\xa2\x02\x03SXX\xaa\x02\aSpotify\xca\x02\aSpotify\xe2\x02\x13Spotify\\GPBMetadata\xea\x02\aSpotify"

var (
	file_spotify_authentication_proto_rawDescOnce sync.Once
	file_spotify_authentication_proto_rawDescData []byte
)

func file_spotify_authentication_proto_rawDescGZIP() []byte {
	file_spotify_authentication_proto_rawDescOnce.Do(func() {
		file_spotify_authentication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spotify_authentication_proto_rawDesc), len(file_spotify_authentication_proto_rawDesc)))
	})
	return file_spotify_authentication_proto_rawDescData
}

var file_spotify_authentication_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_spotify_authentication_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_spotify_authentication_proto_goTypes = []any{
	(AuthenticationType)(0),               // 0: spotify.AuthenticationType
	(AccountCreation)(0),                  // 1: spotify.AccountCreation
	(CpuFamily)(0),                        // 2: spotify.CpuFamily
	(Brand)(0),                            // 3: spotify.Brand
	(Os)(0),                               // 4: spotify.Os
	(AccountType)(0),                      // 5: spotify.AccountType
	(*ClientResponseEncrypted)(nil),       // 6: spotify.ClientResponseEncrypted
	(*LoginCredentials)(nil),              // 7: spotify.LoginCredentials
	(*FingerprintResponseUnion)(nil),      // 8: spotify.FingerprintResponseUnion
	(*FingerprintGrainResponse)(nil),      // 9: spotify.FingerprintGrainResponse
	(*FingerprintHmacRipemdResponse)(nil), // 10: spotify.FingerprintHmacRipemdResponse
	(*PeerTicketUnion)(nil),               // 11: spotify.PeerTicketUnion
	(*PeerTicketPublicKey)(nil),           // 12: spotify.PeerTicketPublicKey
	(*PeerTicketOld)(nil),                 // 13: spotify.PeerTicketOld
	(*SystemInfo)(nil),                    // 14: spotify.SystemInfo
	(*LibspotifyAppKey)(nil),              // 15: spotify.LibspotifyAppKey
	(*ClientInfo)(nil),                    // 16: spotify.ClientInfo
	(*ClientInfoFacebook)(nil),            // 17: spotify.ClientInfoFacebook
	(*APWelcome)(nil),                     // 18: spotify.APWelcome
	(*AccountInfo)(nil),                   // 19: spotify.AccountInfo
	(*AccountInfoSpotify)(nil),            // 20: spotify.AccountInfoSpotify
	(*AccountInfoFacebook)(nil),           // 21: spotify.AccountInfoFacebook
}
var file_spotify_authentication_proto_depIdxs = []int32{
	7,  // 0: spotify.ClientResponseEncrypted.login_credentials:type_name -> spotify.LoginCredentials
	1,  // 1: spotify.ClientResponseEncrypted.account_creation:type_name -> spotify.AccountCreation
	8,  // 2: spotify.ClientResponseEncrypted.fingerprint_response:type_name -> spotify.FingerprintResponseUnion
	11, // 3: spotify.ClientResponseEncrypted.peer_ticket:type_name -> spotify.PeerTicketUnion
	14, // 4: spotify.ClientResponseEncrypted.system_info:type_name -> spotify.SystemInfo
	15, // 5: spotify.ClientResponseEncrypted.appkey:type_name -> spotify.LibspotifyAppKey
	16, // 6: spotify.ClientResponseEncrypted.client_info:type_name -> spotify.ClientInfo
	0,  // 7: spotify.LoginCredentials.typ:type_name -> spotify.AuthenticationType
	9,  // 8: spotify.FingerprintResponseUnion.grain:type_name -> spotify.FingerprintGrainResponse
	10, // 9: spotify.FingerprintResponseUnion.hmac_ripemd:type_name -> spotify.FingerprintHmacRipemdResponse
	12, // 10: spotify.PeerTicketUnion.public_key:type_name -> spotify.PeerTicketPublicKey
	13, // 11: spotify.PeerTicketUnion.old_ticket:type_name -> spotify.PeerTicketOld
	2,  // 12: spotify.SystemInfo.cpu_family:type_name -> spotify.CpuFamily
	3,  // 13: spotify.SystemInfo.brand:type_name -> spotify.Brand
	4,  // 14: spotify.SystemInfo.os:type_name -> spotify.Os
	17, // 15: spotify.ClientInfo.fb:type_name -> spotify.ClientInfoFacebook
	5,  // 16: spotify.APWelcome.account_type_logged_in:type_name -> spotify.AccountType
	5,  // 17: spotify.APWelcome.credentials_type_logged_in:type_name -> spotify.AccountType
	0,  // 18: spotify.APWelcome.reusable_auth_credentials_type:type_name -> spotify.AuthenticationType
	19, // 19: spotify.APWelcome.account_info:type_name -> spotify.AccountInfo
	21, // 20: spotify.APWelcome.fb:type_name -> spotify.AccountInfoFacebook
	20, // 21: spotify.AccountInfo.spotify:type_name -> spotify.AccountInfoSpotify
	21, // 22: spotify.AccountInfo.facebook:type_name -> spotify.AccountInfoFacebook
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_spotify_authentication_proto_init() }
func file_spotify_authentication_proto_init() {
	if File_spotify_authentication_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spotify_authentication_proto_rawDesc), len(file_spotify_authentication_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spotify_authentication_proto_goTypes,
		DependencyIndexes: file_spotify_authentication_proto_depIdxs,
		EnumInfos:         file_spotify_authentication_proto_enumTypes,
		MessageInfos:      file_spotify_authentication_proto_msgTypes,
	}.Build()
	File_spotify_authentication_proto = out.File
	file_spotify_authentication_proto_goTypes = nil
	file_spotify_authentication_proto_depIdxs = nil
}
