// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

//go:build test_unit || test_integration

package player

import (
	"github.com/devgianlu/go-librespot"
	"github.com/devgianlu/go-librespot/audio"
	"github.com/devgianlu/go-librespot/proto/spotify/connectstate"
	"github.com/devgianlu/go-librespot/proto/spotify/metadata"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEventManager creates a new instance of MockEventManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventManager {
	mock := &MockEventManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventManager is an autogenerated mock type for the EventManager type
type MockEventManager struct {
	mock.Mock
}

type MockEventManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventManager) EXPECT() *MockEventManager_Expecter {
	return &MockEventManager_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockEventManager
func (_mock *MockEventManager) Close() {
	_mock.Called()
	return
}

// MockEventManager_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockEventManager_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockEventManager_Expecter) Close() *MockEventManager_Close_Call {
	return &MockEventManager_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockEventManager_Close_Call) Run(run func()) *MockEventManager_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEventManager_Close_Call) Return() *MockEventManager_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventManager_Close_Call) RunAndReturn(run func()) *MockEventManager_Close_Call {
	_c.Run(run)
	return _c
}

// OnPlayerEnd provides a mock function for the type MockEventManager
func (_mock *MockEventManager) OnPlayerEnd(stream *Stream, pos int64) {
	_mock.Called(stream, pos)
	return
}

// MockEventManager_OnPlayerEnd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnPlayerEnd'
type MockEventManager_OnPlayerEnd_Call struct {
	*mock.Call
}

// OnPlayerEnd is a helper method to define mock.On call
//   - stream *Stream
//   - pos int64
func (_e *MockEventManager_Expecter) OnPlayerEnd(stream interface{}, pos interface{}) *MockEventManager_OnPlayerEnd_Call {
	return &MockEventManager_OnPlayerEnd_Call{Call: _e.mock.On("OnPlayerEnd", stream, pos)}
}

func (_c *MockEventManager_OnPlayerEnd_Call) Run(run func(stream *Stream, pos int64)) *MockEventManager_OnPlayerEnd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Stream
		if args[0] != nil {
			arg0 = args[0].(*Stream)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventManager_OnPlayerEnd_Call) Return() *MockEventManager_OnPlayerEnd_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventManager_OnPlayerEnd_Call) RunAndReturn(run func(stream *Stream, pos int64)) *MockEventManager_OnPlayerEnd_Call {
	_c.Run(run)
	return _c
}

// OnPlayerPause provides a mock function for the type MockEventManager
func (_mock *MockEventManager) OnPlayerPause(stream *Stream, ctxUri string, shuffle bool, playOrigin *connectstate.PlayOrigin, track *connectstate.ProvidedTrack, pos int64) {
	_mock.Called(stream, ctxUri, shuffle, playOrigin, track, pos)
	return
}

// MockEventManager_OnPlayerPause_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnPlayerPause'
type MockEventManager_OnPlayerPause_Call struct {
	*mock.Call
}

// OnPlayerPause is a helper method to define mock.On call
//   - stream *Stream
//   - ctxUri string
//   - shuffle bool
//   - playOrigin *connectstate.PlayOrigin
//   - track *connectstate.ProvidedTrack
//   - pos int64
func (_e *MockEventManager_Expecter) OnPlayerPause(stream interface{}, ctxUri interface{}, shuffle interface{}, playOrigin interface{}, track interface{}, pos interface{}) *MockEventManager_OnPlayerPause_Call {
	return &MockEventManager_OnPlayerPause_Call{Call: _e.mock.On("OnPlayerPause", stream, ctxUri, shuffle, playOrigin, track, pos)}
}

func (_c *MockEventManager_OnPlayerPause_Call) Run(run func(stream *Stream, ctxUri string, shuffle bool, playOrigin *connectstate.PlayOrigin, track *connectstate.ProvidedTrack, pos int64)) *MockEventManager_OnPlayerPause_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Stream
		if args[0] != nil {
			arg0 = args[0].(*Stream)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		var arg3 *connectstate.PlayOrigin
		if args[3] != nil {
			arg3 = args[3].(*connectstate.PlayOrigin)
		}
		var arg4 *connectstate.ProvidedTrack
		if args[4] != nil {
			arg4 = args[4].(*connectstate.ProvidedTrack)
		}
		var arg5 int64
		if args[5] != nil {
			arg5 = args[5].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockEventManager_OnPlayerPause_Call) Return() *MockEventManager_OnPlayerPause_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventManager_OnPlayerPause_Call) RunAndReturn(run func(stream *Stream, ctxUri string, shuffle bool, playOrigin *connectstate.PlayOrigin, track *connectstate.ProvidedTrack, pos int64)) *MockEventManager_OnPlayerPause_Call {
	_c.Run(run)
	return _c
}

// OnPlayerPlay provides a mock function for the type MockEventManager
func (_mock *MockEventManager) OnPlayerPlay(stream *Stream, ctxUri string, shuffle bool, playOrigin *connectstate.PlayOrigin, track *connectstate.ProvidedTrack, pos int64) {
	_mock.Called(stream, ctxUri, shuffle, playOrigin, track, pos)
	return
}

// MockEventManager_OnPlayerPlay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnPlayerPlay'
type MockEventManager_OnPlayerPlay_Call struct {
	*mock.Call
}

// OnPlayerPlay is a helper method to define mock.On call
//   - stream *Stream
//   - ctxUri string
//   - shuffle bool
//   - playOrigin *connectstate.PlayOrigin
//   - track *connectstate.ProvidedTrack
//   - pos int64
func (_e *MockEventManager_Expecter) OnPlayerPlay(stream interface{}, ctxUri interface{}, shuffle interface{}, playOrigin interface{}, track interface{}, pos interface{}) *MockEventManager_OnPlayerPlay_Call {
	return &MockEventManager_OnPlayerPlay_Call{Call: _e.mock.On("OnPlayerPlay", stream, ctxUri, shuffle, playOrigin, track, pos)}
}

func (_c *MockEventManager_OnPlayerPlay_Call) Run(run func(stream *Stream, ctxUri string, shuffle bool, playOrigin *connectstate.PlayOrigin, track *connectstate.ProvidedTrack, pos int64)) *MockEventManager_OnPlayerPlay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Stream
		if args[0] != nil {
			arg0 = args[0].(*Stream)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		var arg3 *connectstate.PlayOrigin
		if args[3] != nil {
			arg3 = args[3].(*connectstate.PlayOrigin)
		}
		var arg4 *connectstate.ProvidedTrack
		if args[4] != nil {
			arg4 = args[4].(*connectstate.ProvidedTrack)
		}
		var arg5 int64
		if args[5] != nil {
			arg5 = args[5].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockEventManager_OnPlayerPlay_Call) Return() *MockEventManager_OnPlayerPlay_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventManager_OnPlayerPlay_Call) RunAndReturn(run func(stream *Stream, ctxUri string, shuffle bool, playOrigin *connectstate.PlayOrigin, track *connectstate.ProvidedTrack, pos int64)) *MockEventManager_OnPlayerPlay_Call {
	_c.Run(run)
	return _c
}

// OnPlayerResume provides a mock function for the type MockEventManager
func (_mock *MockEventManager) OnPlayerResume(stream *Stream, pos int64) {
	_mock.Called(stream, pos)
	return
}

// MockEventManager_OnPlayerResume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnPlayerResume'
type MockEventManager_OnPlayerResume_Call struct {
	*mock.Call
}

// OnPlayerResume is a helper method to define mock.On call
//   - stream *Stream
//   - pos int64
func (_e *MockEventManager_Expecter) OnPlayerResume(stream interface{}, pos interface{}) *MockEventManager_OnPlayerResume_Call {
	return &MockEventManager_OnPlayerResume_Call{Call: _e.mock.On("OnPlayerResume", stream, pos)}
}

func (_c *MockEventManager_OnPlayerResume_Call) Run(run func(stream *Stream, pos int64)) *MockEventManager_OnPlayerResume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Stream
		if args[0] != nil {
			arg0 = args[0].(*Stream)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventManager_OnPlayerResume_Call) Return() *MockEventManager_OnPlayerResume_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventManager_OnPlayerResume_Call) RunAndReturn(run func(stream *Stream, pos int64)) *MockEventManager_OnPlayerResume_Call {
	_c.Run(run)
	return _c
}

// OnPlayerSeek provides a mock function for the type MockEventManager
func (_mock *MockEventManager) OnPlayerSeek(stream *Stream, oldPos int64, newPos int64) {
	_mock.Called(stream, oldPos, newPos)
	return
}

// MockEventManager_OnPlayerSeek_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnPlayerSeek'
type MockEventManager_OnPlayerSeek_Call struct {
	*mock.Call
}

// OnPlayerSeek is a helper method to define mock.On call
//   - stream *Stream
//   - oldPos int64
//   - newPos int64
func (_e *MockEventManager_Expecter) OnPlayerSeek(stream interface{}, oldPos interface{}, newPos interface{}) *MockEventManager_OnPlayerSeek_Call {
	return &MockEventManager_OnPlayerSeek_Call{Call: _e.mock.On("OnPlayerSeek", stream, oldPos, newPos)}
}

func (_c *MockEventManager_OnPlayerSeek_Call) Run(run func(stream *Stream, oldPos int64, newPos int64)) *MockEventManager_OnPlayerSeek_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Stream
		if args[0] != nil {
			arg0 = args[0].(*Stream)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEventManager_OnPlayerSeek_Call) Return() *MockEventManager_OnPlayerSeek_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventManager_OnPlayerSeek_Call) RunAndReturn(run func(stream *Stream, oldPos int64, newPos int64)) *MockEventManager_OnPlayerSeek_Call {
	_c.Run(run)
	return _c
}

// OnPlayerSkipBackward provides a mock function for the type MockEventManager
func (_mock *MockEventManager) OnPlayerSkipBackward(stream *Stream, pos int64) {
	_mock.Called(stream, pos)
	return
}

// MockEventManager_OnPlayerSkipBackward_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnPlayerSkipBackward'
type MockEventManager_OnPlayerSkipBackward_Call struct {
	*mock.Call
}

// OnPlayerSkipBackward is a helper method to define mock.On call
//   - stream *Stream
//   - pos int64
func (_e *MockEventManager_Expecter) OnPlayerSkipBackward(stream interface{}, pos interface{}) *MockEventManager_OnPlayerSkipBackward_Call {
	return &MockEventManager_OnPlayerSkipBackward_Call{Call: _e.mock.On("OnPlayerSkipBackward", stream, pos)}
}

func (_c *MockEventManager_OnPlayerSkipBackward_Call) Run(run func(stream *Stream, pos int64)) *MockEventManager_OnPlayerSkipBackward_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Stream
		if args[0] != nil {
			arg0 = args[0].(*Stream)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventManager_OnPlayerSkipBackward_Call) Return() *MockEventManager_OnPlayerSkipBackward_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventManager_OnPlayerSkipBackward_Call) RunAndReturn(run func(stream *Stream, pos int64)) *MockEventManager_OnPlayerSkipBackward_Call {
	_c.Run(run)
	return _c
}

// OnPlayerSkipForward provides a mock function for the type MockEventManager
func (_mock *MockEventManager) OnPlayerSkipForward(stream *Stream, pos int64, skipTo bool) {
	_mock.Called(stream, pos, skipTo)
	return
}

// MockEventManager_OnPlayerSkipForward_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnPlayerSkipForward'
type MockEventManager_OnPlayerSkipForward_Call struct {
	*mock.Call
}

// OnPlayerSkipForward is a helper method to define mock.On call
//   - stream *Stream
//   - pos int64
//   - skipTo bool
func (_e *MockEventManager_Expecter) OnPlayerSkipForward(stream interface{}, pos interface{}, skipTo interface{}) *MockEventManager_OnPlayerSkipForward_Call {
	return &MockEventManager_OnPlayerSkipForward_Call{Call: _e.mock.On("OnPlayerSkipForward", stream, pos, skipTo)}
}

func (_c *MockEventManager_OnPlayerSkipForward_Call) Run(run func(stream *Stream, pos int64, skipTo bool)) *MockEventManager_OnPlayerSkipForward_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Stream
		if args[0] != nil {
			arg0 = args[0].(*Stream)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEventManager_OnPlayerSkipForward_Call) Return() *MockEventManager_OnPlayerSkipForward_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventManager_OnPlayerSkipForward_Call) RunAndReturn(run func(stream *Stream, pos int64, skipTo bool)) *MockEventManager_OnPlayerSkipForward_Call {
	_c.Run(run)
	return _c
}

// OnPrimaryStreamUnload provides a mock function for the type MockEventManager
func (_mock *MockEventManager) OnPrimaryStreamUnload(stream *Stream, pos int64) {
	_mock.Called(stream, pos)
	return
}

// MockEventManager_OnPrimaryStreamUnload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnPrimaryStreamUnload'
type MockEventManager_OnPrimaryStreamUnload_Call struct {
	*mock.Call
}

// OnPrimaryStreamUnload is a helper method to define mock.On call
//   - stream *Stream
//   - pos int64
func (_e *MockEventManager_Expecter) OnPrimaryStreamUnload(stream interface{}, pos interface{}) *MockEventManager_OnPrimaryStreamUnload_Call {
	return &MockEventManager_OnPrimaryStreamUnload_Call{Call: _e.mock.On("OnPrimaryStreamUnload", stream, pos)}
}

func (_c *MockEventManager_OnPrimaryStreamUnload_Call) Run(run func(stream *Stream, pos int64)) *MockEventManager_OnPrimaryStreamUnload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Stream
		if args[0] != nil {
			arg0 = args[0].(*Stream)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventManager_OnPrimaryStreamUnload_Call) Return() *MockEventManager_OnPrimaryStreamUnload_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventManager_OnPrimaryStreamUnload_Call) RunAndReturn(run func(stream *Stream, pos int64)) *MockEventManager_OnPrimaryStreamUnload_Call {
	_c.Run(run)
	return _c
}

// PostPrimaryStreamLoad provides a mock function for the type MockEventManager
func (_mock *MockEventManager) PostPrimaryStreamLoad(stream *Stream, paused bool) {
	_mock.Called(stream, paused)
	return
}

// MockEventManager_PostPrimaryStreamLoad_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostPrimaryStreamLoad'
type MockEventManager_PostPrimaryStreamLoad_Call struct {
	*mock.Call
}

// PostPrimaryStreamLoad is a helper method to define mock.On call
//   - stream *Stream
//   - paused bool
func (_e *MockEventManager_Expecter) PostPrimaryStreamLoad(stream interface{}, paused interface{}) *MockEventManager_PostPrimaryStreamLoad_Call {
	return &MockEventManager_PostPrimaryStreamLoad_Call{Call: _e.mock.On("PostPrimaryStreamLoad", stream, paused)}
}

func (_c *MockEventManager_PostPrimaryStreamLoad_Call) Run(run func(stream *Stream, paused bool)) *MockEventManager_PostPrimaryStreamLoad_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Stream
		if args[0] != nil {
			arg0 = args[0].(*Stream)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventManager_PostPrimaryStreamLoad_Call) Return() *MockEventManager_PostPrimaryStreamLoad_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventManager_PostPrimaryStreamLoad_Call) RunAndReturn(run func(stream *Stream, paused bool)) *MockEventManager_PostPrimaryStreamLoad_Call {
	_c.Run(run)
	return _c
}

// PostStreamInitHttpChunkReader provides a mock function for the type MockEventManager
func (_mock *MockEventManager) PostStreamInitHttpChunkReader(playbackId []byte, reader *audio.HttpChunkedReader) {
	_mock.Called(playbackId, reader)
	return
}

// MockEventManager_PostStreamInitHttpChunkReader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostStreamInitHttpChunkReader'
type MockEventManager_PostStreamInitHttpChunkReader_Call struct {
	*mock.Call
}

// PostStreamInitHttpChunkReader is a helper method to define mock.On call
//   - playbackId []byte
//   - reader *audio.HttpChunkedReader
func (_e *MockEventManager_Expecter) PostStreamInitHttpChunkReader(playbackId interface{}, reader interface{}) *MockEventManager_PostStreamInitHttpChunkReader_Call {
	return &MockEventManager_PostStreamInitHttpChunkReader_Call{Call: _e.mock.On("PostStreamInitHttpChunkReader", playbackId, reader)}
}

func (_c *MockEventManager_PostStreamInitHttpChunkReader_Call) Run(run func(playbackId []byte, reader *audio.HttpChunkedReader)) *MockEventManager_PostStreamInitHttpChunkReader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 *audio.HttpChunkedReader
		if args[1] != nil {
			arg1 = args[1].(*audio.HttpChunkedReader)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventManager_PostStreamInitHttpChunkReader_Call) Return() *MockEventManager_PostStreamInitHttpChunkReader_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventManager_PostStreamInitHttpChunkReader_Call) RunAndReturn(run func(playbackId []byte, reader *audio.HttpChunkedReader)) *MockEventManager_PostStreamInitHttpChunkReader_Call {
	_c.Run(run)
	return _c
}

// PostStreamRequestAudioKey provides a mock function for the type MockEventManager
func (_mock *MockEventManager) PostStreamRequestAudioKey(playbackId []byte) {
	_mock.Called(playbackId)
	return
}

// MockEventManager_PostStreamRequestAudioKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostStreamRequestAudioKey'
type MockEventManager_PostStreamRequestAudioKey_Call struct {
	*mock.Call
}

// PostStreamRequestAudioKey is a helper method to define mock.On call
//   - playbackId []byte
func (_e *MockEventManager_Expecter) PostStreamRequestAudioKey(playbackId interface{}) *MockEventManager_PostStreamRequestAudioKey_Call {
	return &MockEventManager_PostStreamRequestAudioKey_Call{Call: _e.mock.On("PostStreamRequestAudioKey", playbackId)}
}

func (_c *MockEventManager_PostStreamRequestAudioKey_Call) Run(run func(playbackId []byte)) *MockEventManager_PostStreamRequestAudioKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEventManager_PostStreamRequestAudioKey_Call) Return() *MockEventManager_PostStreamRequestAudioKey_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventManager_PostStreamRequestAudioKey_Call) RunAndReturn(run func(playbackId []byte)) *MockEventManager_PostStreamRequestAudioKey_Call {
	_c.Run(run)
	return _c
}

// PostStreamResolveAudioFile provides a mock function for the type MockEventManager
func (_mock *MockEventManager) PostStreamResolveAudioFile(playbackId []byte, targetBitrate int32, media *go_librespot.Media, file *metadata.AudioFile) {
	_mock.Called(playbackId, targetBitrate, media, file)
	return
}

// MockEventManager_PostStreamResolveAudioFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostStreamResolveAudioFile'
type MockEventManager_PostStreamResolveAudioFile_Call struct {
	*mock.Call
}

// PostStreamResolveAudioFile is a helper method to define mock.On call
//   - playbackId []byte
//   - targetBitrate int32
//   - media *go_librespot.Media
//   - file *metadata.AudioFile
func (_e *MockEventManager_Expecter) PostStreamResolveAudioFile(playbackId interface{}, targetBitrate interface{}, media interface{}, file interface{}) *MockEventManager_PostStreamResolveAudioFile_Call {
	return &MockEventManager_PostStreamResolveAudioFile_Call{Call: _e.mock.On("PostStreamResolveAudioFile", playbackId, targetBitrate, media, file)}
}

func (_c *MockEventManager_PostStreamResolveAudioFile_Call) Run(run func(playbackId []byte, targetBitrate int32, media *go_librespot.Media, file *metadata.AudioFile)) *MockEventManager_PostStreamResolveAudioFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		var arg2 *go_librespot.Media
		if args[2] != nil {
			arg2 = args[2].(*go_librespot.Media)
		}
		var arg3 *metadata.AudioFile
		if args[3] != nil {
			arg3 = args[3].(*metadata.AudioFile)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockEventManager_PostStreamResolveAudioFile_Call) Return() *MockEventManager_PostStreamResolveAudioFile_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventManager_PostStreamResolveAudioFile_Call) RunAndReturn(run func(playbackId []byte, targetBitrate int32, media *go_librespot.Media, file *metadata.AudioFile)) *MockEventManager_PostStreamResolveAudioFile_Call {
	_c.Run(run)
	return _c
}

// PostStreamResolveStorage provides a mock function for the type MockEventManager
func (_mock *MockEventManager) PostStreamResolveStorage(playbackId []byte) {
	_mock.Called(playbackId)
	return
}

// MockEventManager_PostStreamResolveStorage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostStreamResolveStorage'
type MockEventManager_PostStreamResolveStorage_Call struct {
	*mock.Call
}

// PostStreamResolveStorage is a helper method to define mock.On call
//   - playbackId []byte
func (_e *MockEventManager_Expecter) PostStreamResolveStorage(playbackId interface{}) *MockEventManager_PostStreamResolveStorage_Call {
	return &MockEventManager_PostStreamResolveStorage_Call{Call: _e.mock.On("PostStreamResolveStorage", playbackId)}
}

func (_c *MockEventManager_PostStreamResolveStorage_Call) Run(run func(playbackId []byte)) *MockEventManager_PostStreamResolveStorage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEventManager_PostStreamResolveStorage_Call) Return() *MockEventManager_PostStreamResolveStorage_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventManager_PostStreamResolveStorage_Call) RunAndReturn(run func(playbackId []byte)) *MockEventManager_PostStreamResolveStorage_Call {
	_c.Run(run)
	return _c
}

// PreStreamLoadNew provides a mock function for the type MockEventManager
func (_mock *MockEventManager) PreStreamLoadNew(playbackId []byte, spotId go_librespot.SpotifyId, mediaPosition int64) {
	_mock.Called(playbackId, spotId, mediaPosition)
	return
}

// MockEventManager_PreStreamLoadNew_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PreStreamLoadNew'
type MockEventManager_PreStreamLoadNew_Call struct {
	*mock.Call
}

// PreStreamLoadNew is a helper method to define mock.On call
//   - playbackId []byte
//   - spotId go_librespot.SpotifyId
//   - mediaPosition int64
func (_e *MockEventManager_Expecter) PreStreamLoadNew(playbackId interface{}, spotId interface{}, mediaPosition interface{}) *MockEventManager_PreStreamLoadNew_Call {
	return &MockEventManager_PreStreamLoadNew_Call{Call: _e.mock.On("PreStreamLoadNew", playbackId, spotId, mediaPosition)}
}

func (_c *MockEventManager_PreStreamLoadNew_Call) Run(run func(playbackId []byte, spotId go_librespot.SpotifyId, mediaPosition int64)) *MockEventManager_PreStreamLoadNew_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 go_librespot.SpotifyId
		if args[1] != nil {
			arg1 = args[1].(go_librespot.SpotifyId)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEventManager_PreStreamLoadNew_Call) Return() *MockEventManager_PreStreamLoadNew_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventManager_PreStreamLoadNew_Call) RunAndReturn(run func(playbackId []byte, spotId go_librespot.SpotifyId, mediaPosition int64)) *MockEventManager_PreStreamLoadNew_Call {
	_c.Run(run)
	return _c
}
