// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

//go:build test_unit || test_integration

package zeroconf

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockServiceRegistrar creates a new instance of MockServiceRegistrar. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServiceRegistrar(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServiceRegistrar {
	mock := &MockServiceRegistrar{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServiceRegistrar is an autogenerated mock type for the ServiceRegistrar type
type MockServiceRegistrar struct {
	mock.Mock
}

type MockServiceRegistrar_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServiceRegistrar) EXPECT() *MockServiceRegistrar_Expecter {
	return &MockServiceRegistrar_Expecter{mock: &_m.Mock}
}

// Register provides a mock function for the type MockServiceRegistrar
func (_mock *MockServiceRegistrar) Register(name string, serviceType string, domain string, port int, txt []string) error {
	ret := _mock.Called(name, serviceType, domain, port, txt)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string, int, []string) error); ok {
		r0 = returnFunc(name, serviceType, domain, port, txt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServiceRegistrar_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockServiceRegistrar_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - name string
//   - serviceType string
//   - domain string
//   - port int
//   - txt []string
func (_e *MockServiceRegistrar_Expecter) Register(name interface{}, serviceType interface{}, domain interface{}, port interface{}, txt interface{}) *MockServiceRegistrar_Register_Call {
	return &MockServiceRegistrar_Register_Call{Call: _e.mock.On("Register", name, serviceType, domain, port, txt)}
}

func (_c *MockServiceRegistrar_Register_Call) Run(run func(name string, serviceType string, domain string, port int, txt []string)) *MockServiceRegistrar_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 []string
		if args[4] != nil {
			arg4 = args[4].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockServiceRegistrar_Register_Call) Return(err error) *MockServiceRegistrar_Register_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServiceRegistrar_Register_Call) RunAndReturn(run func(name string, serviceType string, domain string, port int, txt []string) error) *MockServiceRegistrar_Register_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function for the type MockServiceRegistrar
func (_mock *MockServiceRegistrar) Shutdown() {
	_mock.Called()
	return
}

// MockServiceRegistrar_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockServiceRegistrar_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
func (_e *MockServiceRegistrar_Expecter) Shutdown() *MockServiceRegistrar_Shutdown_Call {
	return &MockServiceRegistrar_Shutdown_Call{Call: _e.mock.On("Shutdown")}
}

func (_c *MockServiceRegistrar_Shutdown_Call) Run(run func()) *MockServiceRegistrar_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServiceRegistrar_Shutdown_Call) Return() *MockServiceRegistrar_Shutdown_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServiceRegistrar_Shutdown_Call) RunAndReturn(run func()) *MockServiceRegistrar_Shutdown_Call {
	_c.Run(run)
	return _c
}

// UpdateName provides a mock function for the type MockServiceRegistrar
func (_mock *MockServiceRegistrar) UpdateName(name string) error {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for UpdateName")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServiceRegistrar_UpdateName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateName'
type MockServiceRegistrar_UpdateName_Call struct {
	*mock.Call
}

// UpdateName is a helper method to define mock.On call
//   - name string
func (_e *MockServiceRegistrar_Expecter) UpdateName(name interface{}) *MockServiceRegistrar_UpdateName_Call {
	return &MockServiceRegistrar_UpdateName_Call{Call: _e.mock.On("UpdateName", name)}
}

func (_c *MockServiceRegistrar_UpdateName_Call) Run(run func(name string)) *MockServiceRegistrar_UpdateName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServiceRegistrar_UpdateName_Call) Return(err error) *MockServiceRegistrar_UpdateName_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServiceRegistrar_UpdateName_Call) RunAndReturn(run func(name string) error) *MockServiceRegistrar_UpdateName_Call {
	_c.Call.Return(run)
	return _c
}
