// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: spotify/extendedmetadata/entity_extension_data.proto

package extendedmetadata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityExtensionDataHeader struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	StatusCode          int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Etag                string                 `protobuf:"bytes,2,opt,name=etag,proto3" json:"etag,omitempty"`
	Locale              string                 `protobuf:"bytes,3,opt,name=locale,proto3" json:"locale,omitempty"`
	CacheTtlInSeconds   int64                  `protobuf:"varint,4,opt,name=cache_ttl_in_seconds,json=cacheTtlInSeconds,proto3" json:"cache_ttl_in_seconds,omitempty"`
	OfflineTtlInSeconds int64                  `protobuf:"varint,5,opt,name=offline_ttl_in_seconds,json=offlineTtlInSeconds,proto3" json:"offline_ttl_in_seconds,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EntityExtensionDataHeader) Reset() {
	*x = EntityExtensionDataHeader{}
	mi := &file_spotify_extendedmetadata_entity_extension_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityExtensionDataHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityExtensionDataHeader) ProtoMessage() {}

func (x *EntityExtensionDataHeader) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_extendedmetadata_entity_extension_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityExtensionDataHeader.ProtoReflect.Descriptor instead.
func (*EntityExtensionDataHeader) Descriptor() ([]byte, []int) {
	return file_spotify_extendedmetadata_entity_extension_data_proto_rawDescGZIP(), []int{0}
}

func (x *EntityExtensionDataHeader) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *EntityExtensionDataHeader) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *EntityExtensionDataHeader) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *EntityExtensionDataHeader) GetCacheTtlInSeconds() int64 {
	if x != nil {
		return x.CacheTtlInSeconds
	}
	return 0
}

func (x *EntityExtensionDataHeader) GetOfflineTtlInSeconds() int64 {
	if x != nil {
		return x.OfflineTtlInSeconds
	}
	return 0
}

type EntityExtensionData struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Header        *EntityExtensionDataHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	EntityUri     string                     `protobuf:"bytes,2,opt,name=entity_uri,json=entityUri,proto3" json:"entity_uri,omitempty"`
	ExtensionData *anypb.Any                 `protobuf:"bytes,3,opt,name=extension_data,json=extensionData,proto3" json:"extension_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityExtensionData) Reset() {
	*x = EntityExtensionData{}
	mi := &file_spotify_extendedmetadata_entity_extension_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityExtensionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityExtensionData) ProtoMessage() {}

func (x *EntityExtensionData) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_extendedmetadata_entity_extension_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityExtensionData.ProtoReflect.Descriptor instead.
func (*EntityExtensionData) Descriptor() ([]byte, []int) {
	return file_spotify_extendedmetadata_entity_extension_data_proto_rawDescGZIP(), []int{1}
}

func (x *EntityExtensionData) GetHeader() *EntityExtensionDataHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *EntityExtensionData) GetEntityUri() string {
	if x != nil {
		return x.EntityUri
	}
	return ""
}

func (x *EntityExtensionData) GetExtensionData() *anypb.Any {
	if x != nil {
		return x.ExtensionData
	}
	return nil
}

type PlainListAssoc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityUri     []string               `protobuf:"bytes,1,rep,name=entity_uri,json=entityUri,proto3" json:"entity_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlainListAssoc) Reset() {
	*x = PlainListAssoc{}
	mi := &file_spotify_extendedmetadata_entity_extension_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlainListAssoc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlainListAssoc) ProtoMessage() {}

func (x *PlainListAssoc) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_extendedmetadata_entity_extension_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlainListAssoc.ProtoReflect.Descriptor instead.
func (*PlainListAssoc) Descriptor() ([]byte, []int) {
	return file_spotify_extendedmetadata_entity_extension_data_proto_rawDescGZIP(), []int{2}
}

func (x *PlainListAssoc) GetEntityUri() []string {
	if x != nil {
		return x.EntityUri
	}
	return nil
}

type AssocHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssocHeader) Reset() {
	*x = AssocHeader{}
	mi := &file_spotify_extendedmetadata_entity_extension_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssocHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssocHeader) ProtoMessage() {}

func (x *AssocHeader) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_extendedmetadata_entity_extension_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssocHeader.ProtoReflect.Descriptor instead.
func (*AssocHeader) Descriptor() ([]byte, []int) {
	return file_spotify_extendedmetadata_entity_extension_data_proto_rawDescGZIP(), []int{3}
}

type Assoc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *AssocHeader           `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	PlainList     *PlainListAssoc        `protobuf:"bytes,2,opt,name=plain_list,json=plainList,proto3" json:"plain_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Assoc) Reset() {
	*x = Assoc{}
	mi := &file_spotify_extendedmetadata_entity_extension_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assoc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assoc) ProtoMessage() {}

func (x *Assoc) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_extendedmetadata_entity_extension_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assoc.ProtoReflect.Descriptor instead.
func (*Assoc) Descriptor() ([]byte, []int) {
	return file_spotify_extendedmetadata_entity_extension_data_proto_rawDescGZIP(), []int{4}
}

func (x *Assoc) GetHeader() *AssocHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Assoc) GetPlainList() *PlainListAssoc {
	if x != nil {
		return x.PlainList
	}
	return nil
}

var File_spotify_extendedmetadata_entity_extension_data_proto protoreflect.FileDescriptor

const file_spotify_extendedmetadata_entity_extension_data_proto_rawDesc = "" +
	"\n" +
	"4spotify/extendedmetadata/entity_extension_data.proto\x12\x18spotify.extendedmetadata\x1a\x19google/protobuf/any.proto\"\xce\x01\n" +
	"\x19EntityExtensionDataHeader\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x12\n" +
	"\x04etag\x18\x02 \x01(\tR\x04etag\x12\x16\n" +
	"\x06locale\x18\x03 \x01(\tR\x06locale\x12/\n" +
	"\x14cache_ttl_in_seconds\x18\x04 \x01(\x03R\x11cacheTtlInSeconds\x123\n" +
	"\x16offline_ttl_in_seconds\x18\x05 \x01(\x03R\x13offlineTtlInSeconds\"\xbe\x01\n" +
	"\x13EntityExtensionData\x12K\n" +
	"\x06header\x18\x01 \x01(\v23.spotify.extendedmetadata.EntityExtensionDataHeaderR\x06header\x12\x1d\n" +
	"\n" +
	"entity_uri\x18\x02 \x01(\tR\tentityUri\x12;\n" +
	"\x0eextension_data\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\rextensionData\"/\n" +
	"\x0ePlainListAssoc\x12\x1d\n" +
	"\n" +
	"entity_uri\x18\x01 \x03(\tR\tentityUri\"\r\n" +
	"\vAssocHeader\"\x8f\x01\n" +
	"\x05Assoc\x12=\n" +
	"\x06header\x18\x01 \x01(\v2%.spotify.extendedmetadata.AssocHeaderR\x06header\x12G\n" +
	"\n" +
	"plain_list\x18\x02 \x01(\v2(.spotify.extendedmetadata.PlainListAssocR\tplainListB\xfb\x01\n" +
	"\x1ccom.spotify.extendedmetadataB\x18EntityExtensionDataProtoP\x01Z@github.com/devgianlu/go-librespot/proto/spotify/extendedmetadata\xa2\x02\x03SEX\xaa\x02\x18Spotify.Extendedmetadata\xca\x02\x18Spotify\\Extendedmetadata\xe2\x02$Spotify\\Extendedmetadata\\GPBMetadata\xea\x02\x19Spotify::Extendedmetadatab\x06proto3"

var (
	file_spotify_extendedmetadata_entity_extension_data_proto_rawDescOnce sync.Once
	file_spotify_extendedmetadata_entity_extension_data_proto_rawDescData []byte
)

func file_spotify_extendedmetadata_entity_extension_data_proto_rawDescGZIP() []byte {
	file_spotify_extendedmetadata_entity_extension_data_proto_rawDescOnce.Do(func() {
		file_spotify_extendedmetadata_entity_extension_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spotify_extendedmetadata_entity_extension_data_proto_rawDesc), len(file_spotify_extendedmetadata_entity_extension_data_proto_rawDesc)))
	})
	return file_spotify_extendedmetadata_entity_extension_data_proto_rawDescData
}

var file_spotify_extendedmetadata_entity_extension_data_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_spotify_extendedmetadata_entity_extension_data_proto_goTypes = []any{
	(*EntityExtensionDataHeader)(nil), // 0: spotify.extendedmetadata.EntityExtensionDataHeader
	(*EntityExtensionData)(nil),       // 1: spotify.extendedmetadata.EntityExtensionData
	(*PlainListAssoc)(nil),            // 2: spotify.extendedmetadata.PlainListAssoc
	(*AssocHeader)(nil),               // 3: spotify.extendedmetadata.AssocHeader
	(*Assoc)(nil),                     // 4: spotify.extendedmetadata.Assoc
	(*anypb.Any)(nil),                 // 5: google.protobuf.Any
}
var file_spotify_extendedmetadata_entity_extension_data_proto_depIdxs = []int32{
	0, // 0: spotify.extendedmetadata.EntityExtensionData.header:type_name -> spotify.extendedmetadata.EntityExtensionDataHeader
	5, // 1: spotify.extendedmetadata.EntityExtensionData.extension_data:type_name -> google.protobuf.Any
	3, // 2: spotify.extendedmetadata.Assoc.header:type_name -> spotify.extendedmetadata.AssocHeader
	2, // 3: spotify.extendedmetadata.Assoc.plain_list:type_name -> spotify.extendedmetadata.PlainListAssoc
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_spotify_extendedmetadata_entity_extension_data_proto_init() }
func file_spotify_extendedmetadata_entity_extension_data_proto_init() {
	if File_spotify_extendedmetadata_entity_extension_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spotify_extendedmetadata_entity_extension_data_proto_rawDesc), len(file_spotify_extendedmetadata_entity_extension_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spotify_extendedmetadata_entity_extension_data_proto_goTypes,
		DependencyIndexes: file_spotify_extendedmetadata_entity_extension_data_proto_depIdxs,
		MessageInfos:      file_spotify_extendedmetadata_entity_extension_data_proto_msgTypes,
	}.Build()
	File_spotify_extendedmetadata_entity_extension_data_proto = out.File
	file_spotify_extendedmetadata_entity_extension_data_proto_goTypes = nil
	file_spotify_extendedmetadata_entity_extension_data_proto_depIdxs = nil
}
