// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: spotify/extendedmetadata/extension_kind.proto

package extendedmetadata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExtensionKind int32

const (
	ExtensionKind_UNKNOWN_EXTENSION            ExtensionKind = 0
	ExtensionKind_CANVAZ                       ExtensionKind = 1
	ExtensionKind_STORYLINES                   ExtensionKind = 2
	ExtensionKind_PODCAST_TOPICS               ExtensionKind = 3
	ExtensionKind_PODCAST_SEGMENTS             ExtensionKind = 4
	ExtensionKind_AUDIO_FILES                  ExtensionKind = 5
	ExtensionKind_TRACK_DESCRIPTOR             ExtensionKind = 6
	ExtensionKind_PODCAST_COUNTER              ExtensionKind = 7
	ExtensionKind_ARTIST_V4                    ExtensionKind = 8
	ExtensionKind_ALBUM_V4                     ExtensionKind = 9
	ExtensionKind_TRACK_V4                     ExtensionKind = 10
	ExtensionKind_SHOW_V4                      ExtensionKind = 11
	ExtensionKind_EPISODE_V4                   ExtensionKind = 12
	ExtensionKind_PODCAST_HTML_DESCRIPTION     ExtensionKind = 13
	ExtensionKind_PODCAST_QUOTES               ExtensionKind = 14
	ExtensionKind_USER_PROFILE                 ExtensionKind = 15
	ExtensionKind_CANVAS_V1                    ExtensionKind = 16
	ExtensionKind_SHOW_V4_BASE                 ExtensionKind = 17
	ExtensionKind_SHOW_V4_EPISODES_ASSOC       ExtensionKind = 18
	ExtensionKind_TRACK_DESCRIPTOR_SIGNATURES  ExtensionKind = 19
	ExtensionKind_PODCAST_AD_SEGMENTS          ExtensionKind = 20
	ExtensionKind_EPISODE_TRANSCRIPTS          ExtensionKind = 21
	ExtensionKind_PODCAST_SUBSCRIPTIONS        ExtensionKind = 22
	ExtensionKind_EXTRACTED_COLOR              ExtensionKind = 23
	ExtensionKind_PODCAST_VIRALITY             ExtensionKind = 24
	ExtensionKind_IMAGE_SPARKLES_HACK          ExtensionKind = 25
	ExtensionKind_PODCAST_POPULARITY_HACK      ExtensionKind = 26
	ExtensionKind_AUTOMIX_MODE                 ExtensionKind = 27
	ExtensionKind_CUEPOINTS                    ExtensionKind = 28
	ExtensionKind_PODCAST_POLL                 ExtensionKind = 29
	ExtensionKind_EPISODE_ACCESS               ExtensionKind = 30
	ExtensionKind_SHOW_ACCESS                  ExtensionKind = 31
	ExtensionKind_PODCAST_QNA                  ExtensionKind = 32
	ExtensionKind_CLIPS                        ExtensionKind = 33
	ExtensionKind_SHOW_V5                      ExtensionKind = 34
	ExtensionKind_EPISODE_V5                   ExtensionKind = 35
	ExtensionKind_PODCAST_CTA_CARDS            ExtensionKind = 36
	ExtensionKind_PODCAST_RATING               ExtensionKind = 37
	ExtensionKind_DISPLAY_SEGMENTS             ExtensionKind = 38
	ExtensionKind_GREENROOM                    ExtensionKind = 39
	ExtensionKind_USER_CREATED                 ExtensionKind = 40
	ExtensionKind_SHOW_DESCRIPTION             ExtensionKind = 41
	ExtensionKind_SHOW_HTML_DESCRIPTION        ExtensionKind = 42
	ExtensionKind_SHOW_PLAYABILITY             ExtensionKind = 43
	ExtensionKind_EPISODE_DESCRIPTION          ExtensionKind = 44
	ExtensionKind_EPISODE_HTML_DESCRIPTION     ExtensionKind = 45
	ExtensionKind_EPISODE_PLAYABILITY          ExtensionKind = 46
	ExtensionKind_SHOW_EPISODES_ASSOC          ExtensionKind = 47
	ExtensionKind_CLIENT_CONFIG                ExtensionKind = 48
	ExtensionKind_PLAYLISTABILITY              ExtensionKind = 49
	ExtensionKind_AUDIOBOOK_V5                 ExtensionKind = 50
	ExtensionKind_CHAPTER_V5                   ExtensionKind = 51
	ExtensionKind_AUDIOBOOK_SPECIFICS          ExtensionKind = 52
	ExtensionKind_EPISODE_RANKING              ExtensionKind = 53
	ExtensionKind_HTML_DESCRIPTION             ExtensionKind = 54
	ExtensionKind_CREATOR_CHANNEL              ExtensionKind = 55
	ExtensionKind_AUDIOBOOK_PROVIDERS          ExtensionKind = 56
	ExtensionKind_PLAY_TRAIT                   ExtensionKind = 57
	ExtensionKind_CONTENT_WARNING              ExtensionKind = 58
	ExtensionKind_IMAGE_CUE                    ExtensionKind = 59
	ExtensionKind_STREAM_COUNT                 ExtensionKind = 60
	ExtensionKind_AUDIO_ATTRIBUTES             ExtensionKind = 61
	ExtensionKind_NAVIGABLE_TRAIT              ExtensionKind = 62
	ExtensionKind_NEXT_BEST_EPISODE            ExtensionKind = 63
	ExtensionKind_AUDIOBOOK_PRICE              ExtensionKind = 64
	ExtensionKind_EXPRESSIVE_PLAYLISTS         ExtensionKind = 65
	ExtensionKind_DYNAMIC_SHOW_EPISODE         ExtensionKind = 66
	ExtensionKind_LIVE                         ExtensionKind = 67
	ExtensionKind_SKIP_PLAYED                  ExtensionKind = 68
	ExtensionKind_AD_BREAK_FREE_PODCASTS       ExtensionKind = 69
	ExtensionKind_ASSOCIATIONS                 ExtensionKind = 70
	ExtensionKind_PLAYLIST_EVALUATION          ExtensionKind = 71
	ExtensionKind_CACHE_INVALIDATIONS          ExtensionKind = 72
	ExtensionKind_LIVESTREAM_ENTITY            ExtensionKind = 73
	ExtensionKind_SINGLE_TAP_REACTIONS         ExtensionKind = 74
	ExtensionKind_USER_COMMENTS                ExtensionKind = 75
	ExtensionKind_CLIENT_RESTRICTIONS          ExtensionKind = 76
	ExtensionKind_PODCAST_GUEST                ExtensionKind = 77
	ExtensionKind_PLAYABILITY                  ExtensionKind = 78
	ExtensionKind_COVER_IMAGE                  ExtensionKind = 79
	ExtensionKind_SHARE_TRAIT                  ExtensionKind = 80
	ExtensionKind_INSTANCE_SHARING             ExtensionKind = 81
	ExtensionKind_ARTIST_TOUR                  ExtensionKind = 82
	ExtensionKind_AUDIOBOOK_GENRE              ExtensionKind = 83
	ExtensionKind_CONCEPT                      ExtensionKind = 84
	ExtensionKind_ORIGINAL_VIDEO               ExtensionKind = 85
	ExtensionKind_SMART_SHUFFLE                ExtensionKind = 86
	ExtensionKind_LIVE_EVENTS                  ExtensionKind = 87
	ExtensionKind_AUDIOBOOK_RELATIONS          ExtensionKind = 88
	ExtensionKind_HOME_POC_BASECARD            ExtensionKind = 89
	ExtensionKind_AUDIOBOOK_SUPPLEMENTS        ExtensionKind = 90
	ExtensionKind_PAID_PODCAST_BANNER          ExtensionKind = 91
	ExtensionKind_FEWER_ADS                    ExtensionKind = 92
	ExtensionKind_WATCH_FEED_SHOW_EXPLORER     ExtensionKind = 93
	ExtensionKind_TRACK_EXTRA_DESCRIPTORS      ExtensionKind = 94
	ExtensionKind_TRACK_EXTRA_AUDIO_ATTRIBUTES ExtensionKind = 95
	ExtensionKind_TRACK_EXTENDED_CREDITS       ExtensionKind = 96
	ExtensionKind_SIMPLE_TRAIT                 ExtensionKind = 97
	ExtensionKind_AUDIO_ASSOCIATIONS           ExtensionKind = 98
	ExtensionKind_VIDEO_ASSOCIATIONS           ExtensionKind = 99
	ExtensionKind_PLAYLIST_TUNER               ExtensionKind = 100
	ExtensionKind_ARTIST_VIDEOS_ENTRYPOINT     ExtensionKind = 101
	ExtensionKind_ALBUM_PRERELEASE             ExtensionKind = 102
	ExtensionKind_CONTENT_ALTERNATIVES         ExtensionKind = 103
	ExtensionKind_SNAPSHOT_SHARING             ExtensionKind = 105
	ExtensionKind_DISPLAY_SEGMENTS_COUNT       ExtensionKind = 106
	ExtensionKind_PODCAST_FEATURED_EPISODE     ExtensionKind = 107
	ExtensionKind_PODCAST_SPONSORED_CONTENT    ExtensionKind = 108
	ExtensionKind_PODCAST_EPISODE_TOPICS_LLM   ExtensionKind = 109
	ExtensionKind_PODCAST_EPISODE_TOPICS_KG    ExtensionKind = 110
	ExtensionKind_EPISODE_RANKING_POPULARITY   ExtensionKind = 111
	ExtensionKind_MERCH                        ExtensionKind = 112
	ExtensionKind_COMPANION_CONTENT            ExtensionKind = 113
	ExtensionKind_WATCH_FEED_ENTITY_EXPLORER   ExtensionKind = 114
	ExtensionKind_ANCHOR_CARD_TRAIT            ExtensionKind = 115
	ExtensionKind_AUDIO_PREVIEW_PLAYBACK_TRAIT ExtensionKind = 116
	ExtensionKind_VIDEO_PREVIEW_STILL_TRAIT    ExtensionKind = 117
	ExtensionKind_PREVIEW_CARD_TRAIT           ExtensionKind = 118
	ExtensionKind_SHORTCUTS_CARD_TRAIT         ExtensionKind = 119
	ExtensionKind_VIDEO_PREVIEW_PLAYBACK_TRAIT ExtensionKind = 120
	ExtensionKind_COURSE_SPECIFICS             ExtensionKind = 121
	ExtensionKind_CONCERT                      ExtensionKind = 122
	ExtensionKind_CONCERT_LOCATION             ExtensionKind = 123
	ExtensionKind_CONCERT_MARKETING            ExtensionKind = 124
	ExtensionKind_CONCERT_PERFORMERS           ExtensionKind = 125
	ExtensionKind_TRACK_PAIR_TRANSITION        ExtensionKind = 126
	ExtensionKind_CONTENT_TYPE_TRAIT           ExtensionKind = 127
	ExtensionKind_NAME_TRAIT                   ExtensionKind = 128
	ExtensionKind_ARTWORK_TRAIT                ExtensionKind = 129
	ExtensionKind_RELEASE_DATE_TRAIT           ExtensionKind = 130
	ExtensionKind_CREDITS_TRAIT                ExtensionKind = 131
	ExtensionKind_RELEASE_URI_TRAIT            ExtensionKind = 132
	ExtensionKind_ENTITY_CAPPING               ExtensionKind = 133
	ExtensionKind_LESSON_SPECIFICS             ExtensionKind = 134
	ExtensionKind_CONCERT_OFFERS               ExtensionKind = 135
	ExtensionKind_TRANSITION_MAPS              ExtensionKind = 136
	ExtensionKind_ARTIST_HAS_CONCERTS          ExtensionKind = 137
	ExtensionKind_PRERELEASE                   ExtensionKind = 138
	ExtensionKind_PLAYLIST_ATTRIBUTES_V2       ExtensionKind = 139
	ExtensionKind_LIST_ATTRIBUTES_V2           ExtensionKind = 140
	ExtensionKind_LIST_METADATA                ExtensionKind = 141
	ExtensionKind_LIST_TUNER_AUDIO_ANALYSIS    ExtensionKind = 142
	ExtensionKind_LIST_TUNER_CUEPOINTS         ExtensionKind = 143
	ExtensionKind_CONTENT_RATING_TRAIT         ExtensionKind = 144
	ExtensionKind_COPYRIGHT_TRAIT              ExtensionKind = 145
	ExtensionKind_SUPPORTED_BADGES             ExtensionKind = 146
	ExtensionKind_BADGES                       ExtensionKind = 147
	ExtensionKind_PREVIEW_TRAIT                ExtensionKind = 148
	ExtensionKind_ROOTLISTABILITY_TRAIT        ExtensionKind = 149
	ExtensionKind_LOCAL_CONCERTS               ExtensionKind = 150
	ExtensionKind_RECOMMENDED_PLAYLISTS        ExtensionKind = 151
	ExtensionKind_POPULAR_RELEASES             ExtensionKind = 152
	ExtensionKind_RELATED_RELEASES             ExtensionKind = 153
	ExtensionKind_SHARE_RESTRICTIONS           ExtensionKind = 154
	ExtensionKind_CONCERT_OFFER                ExtensionKind = 155
	ExtensionKind_CONCERT_OFFER_PROVIDER       ExtensionKind = 156
	ExtensionKind_ENTITY_BOOKMARKS             ExtensionKind = 157
	ExtensionKind_PRIVACY_TRAIT                ExtensionKind = 158
	ExtensionKind_DUPLICATE_ITEMS_TRAIT        ExtensionKind = 159
	ExtensionKind_REORDERING_TRAIT             ExtensionKind = 160
	ExtensionKind_PODCAST_RESUMPTION_SEGMENTS  ExtensionKind = 161
	ExtensionKind_ARTIST_EXPRESSION_VIDEO      ExtensionKind = 162
	ExtensionKind_PRERELEASE_VIDEO             ExtensionKind = 163
	ExtensionKind_GATED_ENTITY_RELATIONS       ExtensionKind = 164
	ExtensionKind_RELATED_CREATORS_SECTION     ExtensionKind = 165
	ExtensionKind_CREATORS_APPEARS_ON_SECTION  ExtensionKind = 166
	ExtensionKind_PROMO_V1_TRAIT               ExtensionKind = 167
	ExtensionKind_SPEECHLESS_SHARE_CARD        ExtensionKind = 168
	ExtensionKind_TOP_PLAYABLES_SECTION        ExtensionKind = 169
	ExtensionKind_AUTO_LENS                    ExtensionKind = 170
	ExtensionKind_PROMO_V3_TRAIT               ExtensionKind = 171
	ExtensionKind_TRACK_CONTENT_FILTER         ExtensionKind = 172
	ExtensionKind_HIGHLIGHTABILITY             ExtensionKind = 173
	ExtensionKind_LINK_CARD_WITH_IMAGE_TRAIT   ExtensionKind = 174
	ExtensionKind_TRACK_CLOUD_SECTION          ExtensionKind = 175
	ExtensionKind_EPISODE_TOPICS               ExtensionKind = 176
	ExtensionKind_VIDEO_THUMBNAIL              ExtensionKind = 177
	ExtensionKind_IDENTITY_TRAIT               ExtensionKind = 178
	ExtensionKind_VISUAL_IDENTITY_TRAIT        ExtensionKind = 179
	ExtensionKind_CONTENT_TYPE_V2_TRAIT        ExtensionKind = 180
	ExtensionKind_PREVIEW_PLAYBACK_TRAIT       ExtensionKind = 181
	ExtensionKind_CONSUMPTION_EXPERIENCE_TRAIT ExtensionKind = 182
	ExtensionKind_PUBLISHING_METADATA_TRAIT    ExtensionKind = 183
	ExtensionKind_DETAILED_EVALUATION_TRAIT    ExtensionKind = 184
	ExtensionKind_ON_PLATFORM_REPUTATION_TRAIT ExtensionKind = 185
	ExtensionKind_CREDITS_V2_TRAIT             ExtensionKind = 186
	ExtensionKind_HIGHLIGHT_PLAYABILITY_TRAIT  ExtensionKind = 187
	ExtensionKind_SHOW_EPISODE_LIST            ExtensionKind = 188
	ExtensionKind_AVAILABLE_RELEASES           ExtensionKind = 189
)

// Enum value maps for ExtensionKind.
var (
	ExtensionKind_name = map[int32]string{
		0:   "UNKNOWN_EXTENSION",
		1:   "CANVAZ",
		2:   "STORYLINES",
		3:   "PODCAST_TOPICS",
		4:   "PODCAST_SEGMENTS",
		5:   "AUDIO_FILES",
		6:   "TRACK_DESCRIPTOR",
		7:   "PODCAST_COUNTER",
		8:   "ARTIST_V4",
		9:   "ALBUM_V4",
		10:  "TRACK_V4",
		11:  "SHOW_V4",
		12:  "EPISODE_V4",
		13:  "PODCAST_HTML_DESCRIPTION",
		14:  "PODCAST_QUOTES",
		15:  "USER_PROFILE",
		16:  "CANVAS_V1",
		17:  "SHOW_V4_BASE",
		18:  "SHOW_V4_EPISODES_ASSOC",
		19:  "TRACK_DESCRIPTOR_SIGNATURES",
		20:  "PODCAST_AD_SEGMENTS",
		21:  "EPISODE_TRANSCRIPTS",
		22:  "PODCAST_SUBSCRIPTIONS",
		23:  "EXTRACTED_COLOR",
		24:  "PODCAST_VIRALITY",
		25:  "IMAGE_SPARKLES_HACK",
		26:  "PODCAST_POPULARITY_HACK",
		27:  "AUTOMIX_MODE",
		28:  "CUEPOINTS",
		29:  "PODCAST_POLL",
		30:  "EPISODE_ACCESS",
		31:  "SHOW_ACCESS",
		32:  "PODCAST_QNA",
		33:  "CLIPS",
		34:  "SHOW_V5",
		35:  "EPISODE_V5",
		36:  "PODCAST_CTA_CARDS",
		37:  "PODCAST_RATING",
		38:  "DISPLAY_SEGMENTS",
		39:  "GREENROOM",
		40:  "USER_CREATED",
		41:  "SHOW_DESCRIPTION",
		42:  "SHOW_HTML_DESCRIPTION",
		43:  "SHOW_PLAYABILITY",
		44:  "EPISODE_DESCRIPTION",
		45:  "EPISODE_HTML_DESCRIPTION",
		46:  "EPISODE_PLAYABILITY",
		47:  "SHOW_EPISODES_ASSOC",
		48:  "CLIENT_CONFIG",
		49:  "PLAYLISTABILITY",
		50:  "AUDIOBOOK_V5",
		51:  "CHAPTER_V5",
		52:  "AUDIOBOOK_SPECIFICS",
		53:  "EPISODE_RANKING",
		54:  "HTML_DESCRIPTION",
		55:  "CREATOR_CHANNEL",
		56:  "AUDIOBOOK_PROVIDERS",
		57:  "PLAY_TRAIT",
		58:  "CONTENT_WARNING",
		59:  "IMAGE_CUE",
		60:  "STREAM_COUNT",
		61:  "AUDIO_ATTRIBUTES",
		62:  "NAVIGABLE_TRAIT",
		63:  "NEXT_BEST_EPISODE",
		64:  "AUDIOBOOK_PRICE",
		65:  "EXPRESSIVE_PLAYLISTS",
		66:  "DYNAMIC_SHOW_EPISODE",
		67:  "LIVE",
		68:  "SKIP_PLAYED",
		69:  "AD_BREAK_FREE_PODCASTS",
		70:  "ASSOCIATIONS",
		71:  "PLAYLIST_EVALUATION",
		72:  "CACHE_INVALIDATIONS",
		73:  "LIVESTREAM_ENTITY",
		74:  "SINGLE_TAP_REACTIONS",
		75:  "USER_COMMENTS",
		76:  "CLIENT_RESTRICTIONS",
		77:  "PODCAST_GUEST",
		78:  "PLAYABILITY",
		79:  "COVER_IMAGE",
		80:  "SHARE_TRAIT",
		81:  "INSTANCE_SHARING",
		82:  "ARTIST_TOUR",
		83:  "AUDIOBOOK_GENRE",
		84:  "CONCEPT",
		85:  "ORIGINAL_VIDEO",
		86:  "SMART_SHUFFLE",
		87:  "LIVE_EVENTS",
		88:  "AUDIOBOOK_RELATIONS",
		89:  "HOME_POC_BASECARD",
		90:  "AUDIOBOOK_SUPPLEMENTS",
		91:  "PAID_PODCAST_BANNER",
		92:  "FEWER_ADS",
		93:  "WATCH_FEED_SHOW_EXPLORER",
		94:  "TRACK_EXTRA_DESCRIPTORS",
		95:  "TRACK_EXTRA_AUDIO_ATTRIBUTES",
		96:  "TRACK_EXTENDED_CREDITS",
		97:  "SIMPLE_TRAIT",
		98:  "AUDIO_ASSOCIATIONS",
		99:  "VIDEO_ASSOCIATIONS",
		100: "PLAYLIST_TUNER",
		101: "ARTIST_VIDEOS_ENTRYPOINT",
		102: "ALBUM_PRERELEASE",
		103: "CONTENT_ALTERNATIVES",
		105: "SNAPSHOT_SHARING",
		106: "DISPLAY_SEGMENTS_COUNT",
		107: "PODCAST_FEATURED_EPISODE",
		108: "PODCAST_SPONSORED_CONTENT",
		109: "PODCAST_EPISODE_TOPICS_LLM",
		110: "PODCAST_EPISODE_TOPICS_KG",
		111: "EPISODE_RANKING_POPULARITY",
		112: "MERCH",
		113: "COMPANION_CONTENT",
		114: "WATCH_FEED_ENTITY_EXPLORER",
		115: "ANCHOR_CARD_TRAIT",
		116: "AUDIO_PREVIEW_PLAYBACK_TRAIT",
		117: "VIDEO_PREVIEW_STILL_TRAIT",
		118: "PREVIEW_CARD_TRAIT",
		119: "SHORTCUTS_CARD_TRAIT",
		120: "VIDEO_PREVIEW_PLAYBACK_TRAIT",
		121: "COURSE_SPECIFICS",
		122: "CONCERT",
		123: "CONCERT_LOCATION",
		124: "CONCERT_MARKETING",
		125: "CONCERT_PERFORMERS",
		126: "TRACK_PAIR_TRANSITION",
		127: "CONTENT_TYPE_TRAIT",
		128: "NAME_TRAIT",
		129: "ARTWORK_TRAIT",
		130: "RELEASE_DATE_TRAIT",
		131: "CREDITS_TRAIT",
		132: "RELEASE_URI_TRAIT",
		133: "ENTITY_CAPPING",
		134: "LESSON_SPECIFICS",
		135: "CONCERT_OFFERS",
		136: "TRANSITION_MAPS",
		137: "ARTIST_HAS_CONCERTS",
		138: "PRERELEASE",
		139: "PLAYLIST_ATTRIBUTES_V2",
		140: "LIST_ATTRIBUTES_V2",
		141: "LIST_METADATA",
		142: "LIST_TUNER_AUDIO_ANALYSIS",
		143: "LIST_TUNER_CUEPOINTS",
		144: "CONTENT_RATING_TRAIT",
		145: "COPYRIGHT_TRAIT",
		146: "SUPPORTED_BADGES",
		147: "BADGES",
		148: "PREVIEW_TRAIT",
		149: "ROOTLISTABILITY_TRAIT",
		150: "LOCAL_CONCERTS",
		151: "RECOMMENDED_PLAYLISTS",
		152: "POPULAR_RELEASES",
		153: "RELATED_RELEASES",
		154: "SHARE_RESTRICTIONS",
		155: "CONCERT_OFFER",
		156: "CONCERT_OFFER_PROVIDER",
		157: "ENTITY_BOOKMARKS",
		158: "PRIVACY_TRAIT",
		159: "DUPLICATE_ITEMS_TRAIT",
		160: "REORDERING_TRAIT",
		161: "PODCAST_RESUMPTION_SEGMENTS",
		162: "ARTIST_EXPRESSION_VIDEO",
		163: "PRERELEASE_VIDEO",
		164: "GATED_ENTITY_RELATIONS",
		165: "RELATED_CREATORS_SECTION",
		166: "CREATORS_APPEARS_ON_SECTION",
		167: "PROMO_V1_TRAIT",
		168: "SPEECHLESS_SHARE_CARD",
		169: "TOP_PLAYABLES_SECTION",
		170: "AUTO_LENS",
		171: "PROMO_V3_TRAIT",
		172: "TRACK_CONTENT_FILTER",
		173: "HIGHLIGHTABILITY",
		174: "LINK_CARD_WITH_IMAGE_TRAIT",
		175: "TRACK_CLOUD_SECTION",
		176: "EPISODE_TOPICS",
		177: "VIDEO_THUMBNAIL",
		178: "IDENTITY_TRAIT",
		179: "VISUAL_IDENTITY_TRAIT",
		180: "CONTENT_TYPE_V2_TRAIT",
		181: "PREVIEW_PLAYBACK_TRAIT",
		182: "CONSUMPTION_EXPERIENCE_TRAIT",
		183: "PUBLISHING_METADATA_TRAIT",
		184: "DETAILED_EVALUATION_TRAIT",
		185: "ON_PLATFORM_REPUTATION_TRAIT",
		186: "CREDITS_V2_TRAIT",
		187: "HIGHLIGHT_PLAYABILITY_TRAIT",
		188: "SHOW_EPISODE_LIST",
		189: "AVAILABLE_RELEASES",
	}
	ExtensionKind_value = map[string]int32{
		"UNKNOWN_EXTENSION":            0,
		"CANVAZ":                       1,
		"STORYLINES":                   2,
		"PODCAST_TOPICS":               3,
		"PODCAST_SEGMENTS":             4,
		"AUDIO_FILES":                  5,
		"TRACK_DESCRIPTOR":             6,
		"PODCAST_COUNTER":              7,
		"ARTIST_V4":                    8,
		"ALBUM_V4":                     9,
		"TRACK_V4":                     10,
		"SHOW_V4":                      11,
		"EPISODE_V4":                   12,
		"PODCAST_HTML_DESCRIPTION":     13,
		"PODCAST_QUOTES":               14,
		"USER_PROFILE":                 15,
		"CANVAS_V1":                    16,
		"SHOW_V4_BASE":                 17,
		"SHOW_V4_EPISODES_ASSOC":       18,
		"TRACK_DESCRIPTOR_SIGNATURES":  19,
		"PODCAST_AD_SEGMENTS":          20,
		"EPISODE_TRANSCRIPTS":          21,
		"PODCAST_SUBSCRIPTIONS":        22,
		"EXTRACTED_COLOR":              23,
		"PODCAST_VIRALITY":             24,
		"IMAGE_SPARKLES_HACK":          25,
		"PODCAST_POPULARITY_HACK":      26,
		"AUTOMIX_MODE":                 27,
		"CUEPOINTS":                    28,
		"PODCAST_POLL":                 29,
		"EPISODE_ACCESS":               30,
		"SHOW_ACCESS":                  31,
		"PODCAST_QNA":                  32,
		"CLIPS":                        33,
		"SHOW_V5":                      34,
		"EPISODE_V5":                   35,
		"PODCAST_CTA_CARDS":            36,
		"PODCAST_RATING":               37,
		"DISPLAY_SEGMENTS":             38,
		"GREENROOM":                    39,
		"USER_CREATED":                 40,
		"SHOW_DESCRIPTION":             41,
		"SHOW_HTML_DESCRIPTION":        42,
		"SHOW_PLAYABILITY":             43,
		"EPISODE_DESCRIPTION":          44,
		"EPISODE_HTML_DESCRIPTION":     45,
		"EPISODE_PLAYABILITY":          46,
		"SHOW_EPISODES_ASSOC":          47,
		"CLIENT_CONFIG":                48,
		"PLAYLISTABILITY":              49,
		"AUDIOBOOK_V5":                 50,
		"CHAPTER_V5":                   51,
		"AUDIOBOOK_SPECIFICS":          52,
		"EPISODE_RANKING":              53,
		"HTML_DESCRIPTION":             54,
		"CREATOR_CHANNEL":              55,
		"AUDIOBOOK_PROVIDERS":          56,
		"PLAY_TRAIT":                   57,
		"CONTENT_WARNING":              58,
		"IMAGE_CUE":                    59,
		"STREAM_COUNT":                 60,
		"AUDIO_ATTRIBUTES":             61,
		"NAVIGABLE_TRAIT":              62,
		"NEXT_BEST_EPISODE":            63,
		"AUDIOBOOK_PRICE":              64,
		"EXPRESSIVE_PLAYLISTS":         65,
		"DYNAMIC_SHOW_EPISODE":         66,
		"LIVE":                         67,
		"SKIP_PLAYED":                  68,
		"AD_BREAK_FREE_PODCASTS":       69,
		"ASSOCIATIONS":                 70,
		"PLAYLIST_EVALUATION":          71,
		"CACHE_INVALIDATIONS":          72,
		"LIVESTREAM_ENTITY":            73,
		"SINGLE_TAP_REACTIONS":         74,
		"USER_COMMENTS":                75,
		"CLIENT_RESTRICTIONS":          76,
		"PODCAST_GUEST":                77,
		"PLAYABILITY":                  78,
		"COVER_IMAGE":                  79,
		"SHARE_TRAIT":                  80,
		"INSTANCE_SHARING":             81,
		"ARTIST_TOUR":                  82,
		"AUDIOBOOK_GENRE":              83,
		"CONCEPT":                      84,
		"ORIGINAL_VIDEO":               85,
		"SMART_SHUFFLE":                86,
		"LIVE_EVENTS":                  87,
		"AUDIOBOOK_RELATIONS":          88,
		"HOME_POC_BASECARD":            89,
		"AUDIOBOOK_SUPPLEMENTS":        90,
		"PAID_PODCAST_BANNER":          91,
		"FEWER_ADS":                    92,
		"WATCH_FEED_SHOW_EXPLORER":     93,
		"TRACK_EXTRA_DESCRIPTORS":      94,
		"TRACK_EXTRA_AUDIO_ATTRIBUTES": 95,
		"TRACK_EXTENDED_CREDITS":       96,
		"SIMPLE_TRAIT":                 97,
		"AUDIO_ASSOCIATIONS":           98,
		"VIDEO_ASSOCIATIONS":           99,
		"PLAYLIST_TUNER":               100,
		"ARTIST_VIDEOS_ENTRYPOINT":     101,
		"ALBUM_PRERELEASE":             102,
		"CONTENT_ALTERNATIVES":         103,
		"SNAPSHOT_SHARING":             105,
		"DISPLAY_SEGMENTS_COUNT":       106,
		"PODCAST_FEATURED_EPISODE":     107,
		"PODCAST_SPONSORED_CONTENT":    108,
		"PODCAST_EPISODE_TOPICS_LLM":   109,
		"PODCAST_EPISODE_TOPICS_KG":    110,
		"EPISODE_RANKING_POPULARITY":   111,
		"MERCH":                        112,
		"COMPANION_CONTENT":            113,
		"WATCH_FEED_ENTITY_EXPLORER":   114,
		"ANCHOR_CARD_TRAIT":            115,
		"AUDIO_PREVIEW_PLAYBACK_TRAIT": 116,
		"VIDEO_PREVIEW_STILL_TRAIT":    117,
		"PREVIEW_CARD_TRAIT":           118,
		"SHORTCUTS_CARD_TRAIT":         119,
		"VIDEO_PREVIEW_PLAYBACK_TRAIT": 120,
		"COURSE_SPECIFICS":             121,
		"CONCERT":                      122,
		"CONCERT_LOCATION":             123,
		"CONCERT_MARKETING":            124,
		"CONCERT_PERFORMERS":           125,
		"TRACK_PAIR_TRANSITION":        126,
		"CONTENT_TYPE_TRAIT":           127,
		"NAME_TRAIT":                   128,
		"ARTWORK_TRAIT":                129,
		"RELEASE_DATE_TRAIT":           130,
		"CREDITS_TRAIT":                131,
		"RELEASE_URI_TRAIT":            132,
		"ENTITY_CAPPING":               133,
		"LESSON_SPECIFICS":             134,
		"CONCERT_OFFERS":               135,
		"TRANSITION_MAPS":              136,
		"ARTIST_HAS_CONCERTS":          137,
		"PRERELEASE":                   138,
		"PLAYLIST_ATTRIBUTES_V2":       139,
		"LIST_ATTRIBUTES_V2":           140,
		"LIST_METADATA":                141,
		"LIST_TUNER_AUDIO_ANALYSIS":    142,
		"LIST_TUNER_CUEPOINTS":         143,
		"CONTENT_RATING_TRAIT":         144,
		"COPYRIGHT_TRAIT":              145,
		"SUPPORTED_BADGES":             146,
		"BADGES":                       147,
		"PREVIEW_TRAIT":                148,
		"ROOTLISTABILITY_TRAIT":        149,
		"LOCAL_CONCERTS":               150,
		"RECOMMENDED_PLAYLISTS":        151,
		"POPULAR_RELEASES":             152,
		"RELATED_RELEASES":             153,
		"SHARE_RESTRICTIONS":           154,
		"CONCERT_OFFER":                155,
		"CONCERT_OFFER_PROVIDER":       156,
		"ENTITY_BOOKMARKS":             157,
		"PRIVACY_TRAIT":                158,
		"DUPLICATE_ITEMS_TRAIT":        159,
		"REORDERING_TRAIT":             160,
		"PODCAST_RESUMPTION_SEGMENTS":  161,
		"ARTIST_EXPRESSION_VIDEO":      162,
		"PRERELEASE_VIDEO":             163,
		"GATED_ENTITY_RELATIONS":       164,
		"RELATED_CREATORS_SECTION":     165,
		"CREATORS_APPEARS_ON_SECTION":  166,
		"PROMO_V1_TRAIT":               167,
		"SPEECHLESS_SHARE_CARD":        168,
		"TOP_PLAYABLES_SECTION":        169,
		"AUTO_LENS":                    170,
		"PROMO_V3_TRAIT":               171,
		"TRACK_CONTENT_FILTER":         172,
		"HIGHLIGHTABILITY":             173,
		"LINK_CARD_WITH_IMAGE_TRAIT":   174,
		"TRACK_CLOUD_SECTION":          175,
		"EPISODE_TOPICS":               176,
		"VIDEO_THUMBNAIL":              177,
		"IDENTITY_TRAIT":               178,
		"VISUAL_IDENTITY_TRAIT":        179,
		"CONTENT_TYPE_V2_TRAIT":        180,
		"PREVIEW_PLAYBACK_TRAIT":       181,
		"CONSUMPTION_EXPERIENCE_TRAIT": 182,
		"PUBLISHING_METADATA_TRAIT":    183,
		"DETAILED_EVALUATION_TRAIT":    184,
		"ON_PLATFORM_REPUTATION_TRAIT": 185,
		"CREDITS_V2_TRAIT":             186,
		"HIGHLIGHT_PLAYABILITY_TRAIT":  187,
		"SHOW_EPISODE_LIST":            188,
		"AVAILABLE_RELEASES":           189,
	}
)

func (x ExtensionKind) Enum() *ExtensionKind {
	p := new(ExtensionKind)
	*p = x
	return p
}

func (x ExtensionKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExtensionKind) Descriptor() protoreflect.EnumDescriptor {
	return file_spotify_extendedmetadata_extension_kind_proto_enumTypes[0].Descriptor()
}

func (ExtensionKind) Type() protoreflect.EnumType {
	return &file_spotify_extendedmetadata_extension_kind_proto_enumTypes[0]
}

func (x ExtensionKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExtensionKind.Descriptor instead.
func (ExtensionKind) EnumDescriptor() ([]byte, []int) {
	return file_spotify_extendedmetadata_extension_kind_proto_rawDescGZIP(), []int{0}
}

var File_spotify_extendedmetadata_extension_kind_proto protoreflect.FileDescriptor

const file_spotify_extendedmetadata_extension_kind_proto_rawDesc = "" +
	"\n" +
	"-spotify/extendedmetadata/extension_kind.proto\x12\x18spotify.extendedmetadata*\x8c\"\n" +
	"\rExtensionKind\x12\x15\n" +
	"\x11UNKNOWN_EXTENSION\x10\x00\x12\n" +
	"\n" +
	"\x06CANVAZ\x10\x01\x12\x0e\n" +
	"\n" +
	"STORYLINES\x10\x02\x12\x12\n" +
	"\x0ePODCAST_TOPICS\x10\x03\x12\x14\n" +
	"\x10PODCAST_SEGMENTS\x10\x04\x12\x0f\n" +
	"\vAUDIO_FILES\x10\x05\x12\x14\n" +
	"\x10TRACK_DESCRIPTOR\x10\x06\x12\x13\n" +
	"\x0fPODCAST_COUNTER\x10\a\x12\r\n" +
	"\tARTIST_V4\x10\b\x12\f\n" +
	"\bALBUM_V4\x10\t\x12\f\n" +
	"\bTRACK_V4\x10\n" +
	"\x12\v\n" +
	"\aSHOW_V4\x10\v\x12\x0e\n" +
	"\n" +
	"EPISODE_V4\x10\f\x12\x1c\n" +
	"\x18PODCAST_HTML_DESCRIPTION\x10\r\x12\x12\n" +
	"\x0ePODCAST_QUOTES\x10\x0e\x12\x10\n" +
	"\fUSER_PROFILE\x10\x0f\x12\r\n" +
	"\tCANVAS_V1\x10\x10\x12\x10\n" +
	"\fSHOW_V4_BASE\x10\x11\x12\x1a\n" +
	"\x16SHOW_V4_EPISODES_ASSOC\x10\x12\x12\x1f\n" +
	"\x1bTRACK_DESCRIPTOR_SIGNATURES\x10\x13\x12\x17\n" +
	"\x13PODCAST_AD_SEGMENTS\x10\x14\x12\x17\n" +
	"\x13EPISODE_TRANSCRIPTS\x10\x15\x12\x19\n" +
	"\x15PODCAST_SUBSCRIPTIONS\x10\x16\x12\x13\n" +
	"\x0fEXTRACTED_COLOR\x10\x17\x12\x14\n" +
	"\x10PODCAST_VIRALITY\x10\x18\x12\x17\n" +
	"\x13IMAGE_SPARKLES_HACK\x10\x19\x12\x1b\n" +
	"\x17PODCAST_POPULARITY_HACK\x10\x1a\x12\x10\n" +
	"\fAUTOMIX_MODE\x10\x1b\x12\r\n" +
	"\tCUEPOINTS\x10\x1c\x12\x10\n" +
	"\fPODCAST_POLL\x10\x1d\x12\x12\n" +
	"\x0eEPISODE_ACCESS\x10\x1e\x12\x0f\n" +
	"\vSHOW_ACCESS\x10\x1f\x12\x0f\n" +
	"\vPODCAST_QNA\x10 \x12\t\n" +
	"\x05CLIPS\x10!\x12\v\n" +
	"\aSHOW_V5\x10\"\x12\x0e\n" +
	"\n" +
	"EPISODE_V5\x10#\x12\x15\n" +
	"\x11PODCAST_CTA_CARDS\x10$\x12\x12\n" +
	"\x0ePODCAST_RATING\x10%\x12\x14\n" +
	"\x10DISPLAY_SEGMENTS\x10&\x12\r\n" +
	"\tGREENROOM\x10'\x12\x10\n" +
	"\fUSER_CREATED\x10(\x12\x14\n" +
	"\x10SHOW_DESCRIPTION\x10)\x12\x19\n" +
	"\x15SHOW_HTML_DESCRIPTION\x10*\x12\x14\n" +
	"\x10SHOW_PLAYABILITY\x10+\x12\x17\n" +
	"\x13EPISODE_DESCRIPTION\x10,\x12\x1c\n" +
	"\x18EPISODE_HTML_DESCRIPTION\x10-\x12\x17\n" +
	"\x13EPISODE_PLAYABILITY\x10.\x12\x17\n" +
	"\x13SHOW_EPISODES_ASSOC\x10/\x12\x11\n" +
	"\rCLIENT_CONFIG\x100\x12\x13\n" +
	"\x0fPLAYLISTABILITY\x101\x12\x10\n" +
	"\fAUDIOBOOK_V5\x102\x12\x0e\n" +
	"\n" +
	"CHAPTER_V5\x103\x12\x17\n" +
	"\x13AUDIOBOOK_SPECIFICS\x104\x12\x13\n" +
	"\x0fEPISODE_RANKING\x105\x12\x14\n" +
	"\x10HTML_DESCRIPTION\x106\x12\x13\n" +
	"\x0fCREATOR_CHANNEL\x107\x12\x17\n" +
	"\x13AUDIOBOOK_PROVIDERS\x108\x12\x0e\n" +
	"\n" +
	"PLAY_TRAIT\x109\x12\x13\n" +
	"\x0fCONTENT_WARNING\x10:\x12\r\n" +
	"\tIMAGE_CUE\x10;\x12\x10\n" +
	"\fSTREAM_COUNT\x10<\x12\x14\n" +
	"\x10AUDIO_ATTRIBUTES\x10=\x12\x13\n" +
	"\x0fNAVIGABLE_TRAIT\x10>\x12\x15\n" +
	"\x11NEXT_BEST_EPISODE\x10?\x12\x13\n" +
	"\x0fAUDIOBOOK_PRICE\x10@\x12\x18\n" +
	"\x14EXPRESSIVE_PLAYLISTS\x10A\x12\x18\n" +
	"\x14DYNAMIC_SHOW_EPISODE\x10B\x12\b\n" +
	"\x04LIVE\x10C\x12\x0f\n" +
	"\vSKIP_PLAYED\x10D\x12\x1a\n" +
	"\x16AD_BREAK_FREE_PODCASTS\x10E\x12\x10\n" +
	"\fASSOCIATIONS\x10F\x12\x17\n" +
	"\x13PLAYLIST_EVALUATION\x10G\x12\x17\n" +
	"\x13CACHE_INVALIDATIONS\x10H\x12\x15\n" +
	"\x11LIVESTREAM_ENTITY\x10I\x12\x18\n" +
	"\x14SINGLE_TAP_REACTIONS\x10J\x12\x11\n" +
	"\rUSER_COMMENTS\x10K\x12\x17\n" +
	"\x13CLIENT_RESTRICTIONS\x10L\x12\x11\n" +
	"\rPODCAST_GUEST\x10M\x12\x0f\n" +
	"\vPLAYABILITY\x10N\x12\x0f\n" +
	"\vCOVER_IMAGE\x10O\x12\x0f\n" +
	"\vSHARE_TRAIT\x10P\x12\x14\n" +
	"\x10INSTANCE_SHARING\x10Q\x12\x0f\n" +
	"\vARTIST_TOUR\x10R\x12\x13\n" +
	"\x0fAUDIOBOOK_GENRE\x10S\x12\v\n" +
	"\aCONCEPT\x10T\x12\x12\n" +
	"\x0eORIGINAL_VIDEO\x10U\x12\x11\n" +
	"\rSMART_SHUFFLE\x10V\x12\x0f\n" +
	"\vLIVE_EVENTS\x10W\x12\x17\n" +
	"\x13AUDIOBOOK_RELATIONS\x10X\x12\x15\n" +
	"\x11HOME_POC_BASECARD\x10Y\x12\x19\n" +
	"\x15AUDIOBOOK_SUPPLEMENTS\x10Z\x12\x17\n" +
	"\x13PAID_PODCAST_BANNER\x10[\x12\r\n" +
	"\tFEWER_ADS\x10\\\x12\x1c\n" +
	"\x18WATCH_FEED_SHOW_EXPLORER\x10]\x12\x1b\n" +
	"\x17TRACK_EXTRA_DESCRIPTORS\x10^\x12 \n" +
	"\x1cTRACK_EXTRA_AUDIO_ATTRIBUTES\x10_\x12\x1a\n" +
	"\x16TRACK_EXTENDED_CREDITS\x10`\x12\x10\n" +
	"\fSIMPLE_TRAIT\x10a\x12\x16\n" +
	"\x12AUDIO_ASSOCIATIONS\x10b\x12\x16\n" +
	"\x12VIDEO_ASSOCIATIONS\x10c\x12\x12\n" +
	"\x0ePLAYLIST_TUNER\x10d\x12\x1c\n" +
	"\x18ARTIST_VIDEOS_ENTRYPOINT\x10e\x12\x14\n" +
	"\x10ALBUM_PRERELEASE\x10f\x12\x18\n" +
	"\x14CONTENT_ALTERNATIVES\x10g\x12\x14\n" +
	"\x10SNAPSHOT_SHARING\x10i\x12\x1a\n" +
	"\x16DISPLAY_SEGMENTS_COUNT\x10j\x12\x1c\n" +
	"\x18PODCAST_FEATURED_EPISODE\x10k\x12\x1d\n" +
	"\x19PODCAST_SPONSORED_CONTENT\x10l\x12\x1e\n" +
	"\x1aPODCAST_EPISODE_TOPICS_LLM\x10m\x12\x1d\n" +
	"\x19PODCAST_EPISODE_TOPICS_KG\x10n\x12\x1e\n" +
	"\x1aEPISODE_RANKING_POPULARITY\x10o\x12\t\n" +
	"\x05MERCH\x10p\x12\x15\n" +
	"\x11COMPANION_CONTENT\x10q\x12\x1e\n" +
	"\x1aWATCH_FEED_ENTITY_EXPLORER\x10r\x12\x15\n" +
	"\x11ANCHOR_CARD_TRAIT\x10s\x12 \n" +
	"\x1cAUDIO_PREVIEW_PLAYBACK_TRAIT\x10t\x12\x1d\n" +
	"\x19VIDEO_PREVIEW_STILL_TRAIT\x10u\x12\x16\n" +
	"\x12PREVIEW_CARD_TRAIT\x10v\x12\x18\n" +
	"\x14SHORTCUTS_CARD_TRAIT\x10w\x12 \n" +
	"\x1cVIDEO_PREVIEW_PLAYBACK_TRAIT\x10x\x12\x14\n" +
	"\x10COURSE_SPECIFICS\x10y\x12\v\n" +
	"\aCONCERT\x10z\x12\x14\n" +
	"\x10CONCERT_LOCATION\x10{\x12\x15\n" +
	"\x11CONCERT_MARKETING\x10|\x12\x16\n" +
	"\x12CONCERT_PERFORMERS\x10}\x12\x19\n" +
	"\x15TRACK_PAIR_TRANSITION\x10~\x12\x16\n" +
	"\x12CONTENT_TYPE_TRAIT\x10\x7f\x12\x0f\n" +
	"\n" +
	"NAME_TRAIT\x10\x80\x01\x12\x12\n" +
	"\rARTWORK_TRAIT\x10\x81\x01\x12\x17\n" +
	"\x12RELEASE_DATE_TRAIT\x10\x82\x01\x12\x12\n" +
	"\rCREDITS_TRAIT\x10\x83\x01\x12\x16\n" +
	"\x11RELEASE_URI_TRAIT\x10\x84\x01\x12\x13\n" +
	"\x0eENTITY_CAPPING\x10\x85\x01\x12\x15\n" +
	"\x10LESSON_SPECIFICS\x10\x86\x01\x12\x13\n" +
	"\x0eCONCERT_OFFERS\x10\x87\x01\x12\x14\n" +
	"\x0fTRANSITION_MAPS\x10\x88\x01\x12\x18\n" +
	"\x13ARTIST_HAS_CONCERTS\x10\x89\x01\x12\x0f\n" +
	"\n" +
	"PRERELEASE\x10\x8a\x01\x12\x1b\n" +
	"\x16PLAYLIST_ATTRIBUTES_V2\x10\x8b\x01\x12\x17\n" +
	"\x12LIST_ATTRIBUTES_V2\x10\x8c\x01\x12\x12\n" +
	"\rLIST_METADATA\x10\x8d\x01\x12\x1e\n" +
	"\x19LIST_TUNER_AUDIO_ANALYSIS\x10\x8e\x01\x12\x19\n" +
	"\x14LIST_TUNER_CUEPOINTS\x10\x8f\x01\x12\x19\n" +
	"\x14CONTENT_RATING_TRAIT\x10\x90\x01\x12\x14\n" +
	"\x0fCOPYRIGHT_TRAIT\x10\x91\x01\x12\x15\n" +
	"\x10SUPPORTED_BADGES\x10\x92\x01\x12\v\n" +
	"\x06BADGES\x10\x93\x01\x12\x12\n" +
	"\rPREVIEW_TRAIT\x10\x94\x01\x12\x1a\n" +
	"\x15ROOTLISTABILITY_TRAIT\x10\x95\x01\x12\x13\n" +
	"\x0eLOCAL_CONCERTS\x10\x96\x01\x12\x1a\n" +
	"\x15RECOMMENDED_PLAYLISTS\x10\x97\x01\x12\x15\n" +
	"\x10POPULAR_RELEASES\x10\x98\x01\x12\x15\n" +
	"\x10RELATED_RELEASES\x10\x99\x01\x12\x17\n" +
	"\x12SHARE_RESTRICTIONS\x10\x9a\x01\x12\x12\n" +
	"\rCONCERT_OFFER\x10\x9b\x01\x12\x1b\n" +
	"\x16CONCERT_OFFER_PROVIDER\x10\x9c\x01\x12\x15\n" +
	"\x10ENTITY_BOOKMARKS\x10\x9d\x01\x12\x12\n" +
	"\rPRIVACY_TRAIT\x10\x9e\x01\x12\x1a\n" +
	"\x15DUPLICATE_ITEMS_TRAIT\x10\x9f\x01\x12\x15\n" +
	"\x10REORDERING_TRAIT\x10\xa0\x01\x12 \n" +
	"\x1bPODCAST_RESUMPTION_SEGMENTS\x10\xa1\x01\x12\x1c\n" +
	"\x17ARTIST_EXPRESSION_VIDEO\x10\xa2\x01\x12\x15\n" +
	"\x10PRERELEASE_VIDEO\x10\xa3\x01\x12\x1b\n" +
	"\x16GATED_ENTITY_RELATIONS\x10\xa4\x01\x12\x1d\n" +
	"\x18RELATED_CREATORS_SECTION\x10\xa5\x01\x12 \n" +
	"\x1bCREATORS_APPEARS_ON_SECTION\x10\xa6\x01\x12\x13\n" +
	"\x0ePROMO_V1_TRAIT\x10\xa7\x01\x12\x1a\n" +
	"\x15SPEECHLESS_SHARE_CARD\x10\xa8\x01\x12\x1a\n" +
	"\x15TOP_PLAYABLES_SECTION\x10\xa9\x01\x12\x0e\n" +
	"\tAUTO_LENS\x10\xaa\x01\x12\x13\n" +
	"\x0ePROMO_V3_TRAIT\x10\xab\x01\x12\x19\n" +
	"\x14TRACK_CONTENT_FILTER\x10\xac\x01\x12\x15\n" +
	"\x10HIGHLIGHTABILITY\x10\xad\x01\x12\x1f\n" +
	"\x1aLINK_CARD_WITH_IMAGE_TRAIT\x10\xae\x01\x12\x18\n" +
	"\x13TRACK_CLOUD_SECTION\x10\xaf\x01\x12\x13\n" +
	"\x0eEPISODE_TOPICS\x10\xb0\x01\x12\x14\n" +
	"\x0fVIDEO_THUMBNAIL\x10\xb1\x01\x12\x13\n" +
	"\x0eIDENTITY_TRAIT\x10\xb2\x01\x12\x1a\n" +
	"\x15VISUAL_IDENTITY_TRAIT\x10\xb3\x01\x12\x1a\n" +
	"\x15CONTENT_TYPE_V2_TRAIT\x10\xb4\x01\x12\x1b\n" +
	"\x16PREVIEW_PLAYBACK_TRAIT\x10\xb5\x01\x12!\n" +
	"\x1cCONSUMPTION_EXPERIENCE_TRAIT\x10\xb6\x01\x12\x1e\n" +
	"\x19PUBLISHING_METADATA_TRAIT\x10\xb7\x01\x12\x1e\n" +
	"\x19DETAILED_EVALUATION_TRAIT\x10\xb8\x01\x12!\n" +
	"\x1cON_PLATFORM_REPUTATION_TRAIT\x10\xb9\x01\x12\x15\n" +
	"\x10CREDITS_V2_TRAIT\x10\xba\x01\x12 \n" +
	"\x1bHIGHLIGHT_PLAYABILITY_TRAIT\x10\xbb\x01\x12\x16\n" +
	"\x11SHOW_EPISODE_LIST\x10\xbc\x01\x12\x17\n" +
	"\x12AVAILABLE_RELEASES\x10\xbd\x01B\xf5\x01\n" +
	"\x1ccom.spotify.extendedmetadataB\x12ExtensionKindProtoP\x01Z@github.com/devgianlu/go-librespot/proto/spotify/extendedmetadata\xa2\x02\x03SEX\xaa\x02\x18Spotify.Extendedmetadata\xca\x02\x18Spotify\\Extendedmetadata\xe2\x02$Spotify\\Extendedmetadata\\GPBMetadata\xea\x02\x19Spotify::Extendedmetadatab\x06proto3"

var (
	file_spotify_extendedmetadata_extension_kind_proto_rawDescOnce sync.Once
	file_spotify_extendedmetadata_extension_kind_proto_rawDescData []byte
)

func file_spotify_extendedmetadata_extension_kind_proto_rawDescGZIP() []byte {
	file_spotify_extendedmetadata_extension_kind_proto_rawDescOnce.Do(func() {
		file_spotify_extendedmetadata_extension_kind_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spotify_extendedmetadata_extension_kind_proto_rawDesc), len(file_spotify_extendedmetadata_extension_kind_proto_rawDesc)))
	})
	return file_spotify_extendedmetadata_extension_kind_proto_rawDescData
}

var file_spotify_extendedmetadata_extension_kind_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_spotify_extendedmetadata_extension_kind_proto_goTypes = []any{
	(ExtensionKind)(0), // 0: spotify.extendedmetadata.ExtensionKind
}
var file_spotify_extendedmetadata_extension_kind_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_spotify_extendedmetadata_extension_kind_proto_init() }
func file_spotify_extendedmetadata_extension_kind_proto_init() {
	if File_spotify_extendedmetadata_extension_kind_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spotify_extendedmetadata_extension_kind_proto_rawDesc), len(file_spotify_extendedmetadata_extension_kind_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spotify_extendedmetadata_extension_kind_proto_goTypes,
		DependencyIndexes: file_spotify_extendedmetadata_extension_kind_proto_depIdxs,
		EnumInfos:         file_spotify_extendedmetadata_extension_kind_proto_enumTypes,
	}.Build()
	File_spotify_extendedmetadata_extension_kind_proto = out.File
	file_spotify_extendedmetadata_extension_kind_proto_goTypes = nil
	file_spotify_extendedmetadata_extension_kind_proto_depIdxs = nil
}
