// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: spotify/collection/v2/collection.proto

package collectionv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CollectionItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	AddedAt       int64                  `protobuf:"varint,2,opt,name=added_at,json=addedAt,proto3" json:"added_at,omitempty"`
	IsRemoved     bool                   `protobuf:"varint,3,opt,name=is_removed,json=isRemoved,proto3" json:"is_removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectionItem) Reset() {
	*x = CollectionItem{}
	mi := &file_spotify_collection_v2_collection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionItem) ProtoMessage() {}

func (x *CollectionItem) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_collection_v2_collection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionItem.ProtoReflect.Descriptor instead.
func (*CollectionItem) Descriptor() ([]byte, []int) {
	return file_spotify_collection_v2_collection_proto_rawDescGZIP(), []int{0}
}

func (x *CollectionItem) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *CollectionItem) GetAddedAt() int64 {
	if x != nil {
		return x.AddedAt
	}
	return 0
}

func (x *CollectionItem) GetIsRemoved() bool {
	if x != nil {
		return x.IsRemoved
	}
	return false
}

type WriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Set           string                 `protobuf:"bytes,2,opt,name=set,proto3" json:"set,omitempty"`
	Items         []*CollectionItem      `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_spotify_collection_v2_collection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_collection_v2_collection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_spotify_collection_v2_collection_proto_rawDescGZIP(), []int{1}
}

func (x *WriteRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *WriteRequest) GetSet() string {
	if x != nil {
		return x.Set
	}
	return ""
}

func (x *WriteRequest) GetItems() []*CollectionItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_spotify_collection_v2_collection_proto protoreflect.FileDescriptor

const file_spotify_collection_v2_collection_proto_rawDesc = "" +
	"\n" +
	"&spotify/collection/v2/collection.proto\x12\x15spotify.collection.v2\"\\\n" +
	"\x0eCollectionItem\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12\x19\n" +
	"\badded_at\x18\x02 \x01(\x03R\aaddedAt\x12\x1d\n" +
	"\n" +
	"is_removed\x18\x03 \x01(\bR\tisRemoved\"y\n" +
	"\fWriteRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x10\n" +
	"\x03set\x18\x02 \x01(\tR\x03set\x12;\n" +
	"\x05items\x18\x03 \x03(\v2%.spotify.collection.v2.CollectionItemR\x05itemsB\xee\x01\n" +
	"\x19com.spotify.collection.v2B\x0fCollectionProtoP\x01ZJgithub.com/devgianlu/go-librespot/proto/spotify/collection/v2;collectionv2\xa2\x02\x03SCX\xaa\x02\x15Spotify.Collection.V2\xca\x02\x15Spotify\\Collection\\V2\xe2\x02!Spotify\\Collection\\V2\\GPBMetadata\xea\x02\x17Spotify::Collection::V2b\x06proto3"

var (
	file_spotify_collection_v2_collection_proto_rawDescOnce sync.Once
	file_spotify_collection_v2_collection_proto_rawDescData []byte
)

func file_spotify_collection_v2_collection_proto_rawDescGZIP() []byte {
	file_spotify_collection_v2_collection_proto_rawDescOnce.Do(func() {
		file_spotify_collection_v2_collection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spotify_collection_v2_collection_proto_rawDesc), len(file_spotify_collection_v2_collection_proto_rawDesc)))
	})
	return file_spotify_collection_v2_collection_proto_rawDescData
}

var file_spotify_collection_v2_collection_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_spotify_collection_v2_collection_proto_goTypes = []any{
	(*CollectionItem)(nil), // 0: spotify.collection.v2.CollectionItem
	(*WriteRequest)(nil),   // 1: spotify.collection.v2.WriteRequest
}
var file_spotify_collection_v2_collection_proto_depIdxs = []int32{
	0, // 0: spotify.collection.v2.WriteRequest.items:type_name -> spotify.collection.v2.CollectionItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_spotify_collection_v2_collection_proto_init() }
func file_spotify_collection_v2_collection_proto_init() {
	if File_spotify_collection_v2_collection_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spotify_collection_v2_collection_proto_rawDesc), len(file_spotify_collection_v2_collection_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spotify_collection_v2_collection_proto_goTypes,
		DependencyIndexes: file_spotify_collection_v2_collection_proto_depIdxs,
		MessageInfos:      file_spotify_collection_v2_collection_proto_msgTypes,
	}.Build()
	File_spotify_collection_v2_collection_proto = out.File
	file_spotify_collection_v2_collection_proto_goTypes = nil
	file_spotify_collection_v2_collection_proto_depIdxs = nil
}
