// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: spotify/login5/v3/login5.proto

package login5v3

import (
	challenges "github.com/devgianlu/go-librespot/proto/spotify/login5/v3/challenges"
	credentials "github.com/devgianlu/go-librespot/proto/spotify/login5/v3/credentials"
	identifiers "github.com/devgianlu/go-librespot/proto/spotify/login5/v3/identifiers"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginError int32

const (
	LoginError_UNKNOWN_ERROR              LoginError = 0
	LoginError_INVALID_CREDENTIALS        LoginError = 1
	LoginError_BAD_REQUEST                LoginError = 2
	LoginError_UNSUPPORTED_LOGIN_PROTOCOL LoginError = 3
	LoginError_TIMEOUT                    LoginError = 4
	LoginError_UNKNOWN_IDENTIFIER         LoginError = 5
	LoginError_TOO_MANY_ATTEMPTS          LoginError = 6
	LoginError_INVALID_PHONENUMBER        LoginError = 7
	LoginError_TRY_AGAIN_LATER            LoginError = 8
)

// Enum value maps for LoginError.
var (
	LoginError_name = map[int32]string{
		0: "UNKNOWN_ERROR",
		1: "INVALID_CREDENTIALS",
		2: "BAD_REQUEST",
		3: "UNSUPPORTED_LOGIN_PROTOCOL",
		4: "TIMEOUT",
		5: "UNKNOWN_IDENTIFIER",
		6: "TOO_MANY_ATTEMPTS",
		7: "INVALID_PHONENUMBER",
		8: "TRY_AGAIN_LATER",
	}
	LoginError_value = map[string]int32{
		"UNKNOWN_ERROR":              0,
		"INVALID_CREDENTIALS":        1,
		"BAD_REQUEST":                2,
		"UNSUPPORTED_LOGIN_PROTOCOL": 3,
		"TIMEOUT":                    4,
		"UNKNOWN_IDENTIFIER":         5,
		"TOO_MANY_ATTEMPTS":          6,
		"INVALID_PHONENUMBER":        7,
		"TRY_AGAIN_LATER":            8,
	}
)

func (x LoginError) Enum() *LoginError {
	p := new(LoginError)
	*p = x
	return p
}

func (x LoginError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoginError) Descriptor() protoreflect.EnumDescriptor {
	return file_spotify_login5_v3_login5_proto_enumTypes[0].Descriptor()
}

func (LoginError) Type() protoreflect.EnumType {
	return &file_spotify_login5_v3_login5_proto_enumTypes[0]
}

func (x LoginError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoginError.Descriptor instead.
func (LoginError) EnumDescriptor() ([]byte, []int) {
	return file_spotify_login5_v3_login5_proto_rawDescGZIP(), []int{0}
}

type LoginResponse_Warnings int32

const (
	LoginResponse_UNKNOWN_WARNING             LoginResponse_Warnings = 0
	LoginResponse_DEPRECATED_PROTOCOL_VERSION LoginResponse_Warnings = 1
)

// Enum value maps for LoginResponse_Warnings.
var (
	LoginResponse_Warnings_name = map[int32]string{
		0: "UNKNOWN_WARNING",
		1: "DEPRECATED_PROTOCOL_VERSION",
	}
	LoginResponse_Warnings_value = map[string]int32{
		"UNKNOWN_WARNING":             0,
		"DEPRECATED_PROTOCOL_VERSION": 1,
	}
)

func (x LoginResponse_Warnings) Enum() *LoginResponse_Warnings {
	p := new(LoginResponse_Warnings)
	*p = x
	return p
}

func (x LoginResponse_Warnings) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoginResponse_Warnings) Descriptor() protoreflect.EnumDescriptor {
	return file_spotify_login5_v3_login5_proto_enumTypes[1].Descriptor()
}

func (LoginResponse_Warnings) Type() protoreflect.EnumType {
	return &file_spotify_login5_v3_login5_proto_enumTypes[1]
}

func (x LoginResponse_Warnings) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoginResponse_Warnings.Descriptor instead.
func (LoginResponse_Warnings) EnumDescriptor() ([]byte, []int) {
	return file_spotify_login5_v3_login5_proto_rawDescGZIP(), []int{6, 0}
}

type Challenges struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Challenges    []*Challenge           `protobuf:"bytes,1,rep,name=challenges,proto3" json:"challenges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Challenges) Reset() {
	*x = Challenges{}
	mi := &file_spotify_login5_v3_login5_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Challenges) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Challenges) ProtoMessage() {}

func (x *Challenges) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_login5_v3_login5_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Challenges.ProtoReflect.Descriptor instead.
func (*Challenges) Descriptor() ([]byte, []int) {
	return file_spotify_login5_v3_login5_proto_rawDescGZIP(), []int{0}
}

func (x *Challenges) GetChallenges() []*Challenge {
	if x != nil {
		return x.Challenges
	}
	return nil
}

type Challenge struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Challenge:
	//
	//	*Challenge_Hashcash
	//	*Challenge_Code
	Challenge     isChallenge_Challenge `protobuf_oneof:"challenge"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Challenge) Reset() {
	*x = Challenge{}
	mi := &file_spotify_login5_v3_login5_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Challenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Challenge) ProtoMessage() {}

func (x *Challenge) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_login5_v3_login5_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Challenge.ProtoReflect.Descriptor instead.
func (*Challenge) Descriptor() ([]byte, []int) {
	return file_spotify_login5_v3_login5_proto_rawDescGZIP(), []int{1}
}

func (x *Challenge) GetChallenge() isChallenge_Challenge {
	if x != nil {
		return x.Challenge
	}
	return nil
}

func (x *Challenge) GetHashcash() *challenges.HashcashChallenge {
	if x != nil {
		if x, ok := x.Challenge.(*Challenge_Hashcash); ok {
			return x.Hashcash
		}
	}
	return nil
}

func (x *Challenge) GetCode() *challenges.CodeChallenge {
	if x != nil {
		if x, ok := x.Challenge.(*Challenge_Code); ok {
			return x.Code
		}
	}
	return nil
}

type isChallenge_Challenge interface {
	isChallenge_Challenge()
}

type Challenge_Hashcash struct {
	Hashcash *challenges.HashcashChallenge `protobuf:"bytes,1,opt,name=hashcash,proto3,oneof"`
}

type Challenge_Code struct {
	Code *challenges.CodeChallenge `protobuf:"bytes,2,opt,name=code,proto3,oneof"`
}

func (*Challenge_Hashcash) isChallenge_Challenge() {}

func (*Challenge_Code) isChallenge_Challenge() {}

type ChallengeSolutions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Solutions     []*ChallengeSolution   `protobuf:"bytes,1,rep,name=solutions,proto3" json:"solutions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChallengeSolutions) Reset() {
	*x = ChallengeSolutions{}
	mi := &file_spotify_login5_v3_login5_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeSolutions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeSolutions) ProtoMessage() {}

func (x *ChallengeSolutions) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_login5_v3_login5_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeSolutions.ProtoReflect.Descriptor instead.
func (*ChallengeSolutions) Descriptor() ([]byte, []int) {
	return file_spotify_login5_v3_login5_proto_rawDescGZIP(), []int{2}
}

func (x *ChallengeSolutions) GetSolutions() []*ChallengeSolution {
	if x != nil {
		return x.Solutions
	}
	return nil
}

type ChallengeSolution struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Solution:
	//
	//	*ChallengeSolution_Hashcash
	//	*ChallengeSolution_Code
	Solution      isChallengeSolution_Solution `protobuf_oneof:"solution"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChallengeSolution) Reset() {
	*x = ChallengeSolution{}
	mi := &file_spotify_login5_v3_login5_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeSolution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeSolution) ProtoMessage() {}

func (x *ChallengeSolution) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_login5_v3_login5_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeSolution.ProtoReflect.Descriptor instead.
func (*ChallengeSolution) Descriptor() ([]byte, []int) {
	return file_spotify_login5_v3_login5_proto_rawDescGZIP(), []int{3}
}

func (x *ChallengeSolution) GetSolution() isChallengeSolution_Solution {
	if x != nil {
		return x.Solution
	}
	return nil
}

func (x *ChallengeSolution) GetHashcash() *challenges.HashcashSolution {
	if x != nil {
		if x, ok := x.Solution.(*ChallengeSolution_Hashcash); ok {
			return x.Hashcash
		}
	}
	return nil
}

func (x *ChallengeSolution) GetCode() *challenges.CodeSolution {
	if x != nil {
		if x, ok := x.Solution.(*ChallengeSolution_Code); ok {
			return x.Code
		}
	}
	return nil
}

type isChallengeSolution_Solution interface {
	isChallengeSolution_Solution()
}

type ChallengeSolution_Hashcash struct {
	Hashcash *challenges.HashcashSolution `protobuf:"bytes,1,opt,name=hashcash,proto3,oneof"`
}

type ChallengeSolution_Code struct {
	Code *challenges.CodeSolution `protobuf:"bytes,2,opt,name=code,proto3,oneof"`
}

func (*ChallengeSolution_Hashcash) isChallengeSolution_Solution() {}

func (*ChallengeSolution_Code) isChallengeSolution_Solution() {}

type LoginRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ClientInfo         *ClientInfo            `protobuf:"bytes,1,opt,name=client_info,json=clientInfo,proto3" json:"client_info,omitempty"`
	LoginContext       []byte                 `protobuf:"bytes,2,opt,name=login_context,json=loginContext,proto3" json:"login_context,omitempty"`
	ChallengeSolutions *ChallengeSolutions    `protobuf:"bytes,3,opt,name=challenge_solutions,json=challengeSolutions,proto3" json:"challenge_solutions,omitempty"`
	// Types that are valid to be assigned to LoginMethod:
	//
	//	*LoginRequest_StoredCredential
	//	*LoginRequest_Password
	//	*LoginRequest_FacebookAccessToken
	//	*LoginRequest_PhoneNumber
	//	*LoginRequest_OneTimeToken
	//	*LoginRequest_ParentChildCredential
	//	*LoginRequest_AppleSignInCredential
	//	*LoginRequest_SamsungSignInCredential
	//	*LoginRequest_GoogleSignInCredential
	LoginMethod   isLoginRequest_LoginMethod `protobuf_oneof:"login_method"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_spotify_login5_v3_login5_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_login5_v3_login5_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_spotify_login5_v3_login5_proto_rawDescGZIP(), []int{4}
}

func (x *LoginRequest) GetClientInfo() *ClientInfo {
	if x != nil {
		return x.ClientInfo
	}
	return nil
}

func (x *LoginRequest) GetLoginContext() []byte {
	if x != nil {
		return x.LoginContext
	}
	return nil
}

func (x *LoginRequest) GetChallengeSolutions() *ChallengeSolutions {
	if x != nil {
		return x.ChallengeSolutions
	}
	return nil
}

func (x *LoginRequest) GetLoginMethod() isLoginRequest_LoginMethod {
	if x != nil {
		return x.LoginMethod
	}
	return nil
}

func (x *LoginRequest) GetStoredCredential() *credentials.StoredCredential {
	if x != nil {
		if x, ok := x.LoginMethod.(*LoginRequest_StoredCredential); ok {
			return x.StoredCredential
		}
	}
	return nil
}

func (x *LoginRequest) GetPassword() *credentials.Password {
	if x != nil {
		if x, ok := x.LoginMethod.(*LoginRequest_Password); ok {
			return x.Password
		}
	}
	return nil
}

func (x *LoginRequest) GetFacebookAccessToken() *credentials.FacebookAccessToken {
	if x != nil {
		if x, ok := x.LoginMethod.(*LoginRequest_FacebookAccessToken); ok {
			return x.FacebookAccessToken
		}
	}
	return nil
}

func (x *LoginRequest) GetPhoneNumber() *identifiers.PhoneNumber {
	if x != nil {
		if x, ok := x.LoginMethod.(*LoginRequest_PhoneNumber); ok {
			return x.PhoneNumber
		}
	}
	return nil
}

func (x *LoginRequest) GetOneTimeToken() *credentials.OneTimeToken {
	if x != nil {
		if x, ok := x.LoginMethod.(*LoginRequest_OneTimeToken); ok {
			return x.OneTimeToken
		}
	}
	return nil
}

func (x *LoginRequest) GetParentChildCredential() *credentials.ParentChildCredential {
	if x != nil {
		if x, ok := x.LoginMethod.(*LoginRequest_ParentChildCredential); ok {
			return x.ParentChildCredential
		}
	}
	return nil
}

func (x *LoginRequest) GetAppleSignInCredential() *credentials.AppleSignInCredential {
	if x != nil {
		if x, ok := x.LoginMethod.(*LoginRequest_AppleSignInCredential); ok {
			return x.AppleSignInCredential
		}
	}
	return nil
}

func (x *LoginRequest) GetSamsungSignInCredential() *credentials.SamsungSignInCredential {
	if x != nil {
		if x, ok := x.LoginMethod.(*LoginRequest_SamsungSignInCredential); ok {
			return x.SamsungSignInCredential
		}
	}
	return nil
}

func (x *LoginRequest) GetGoogleSignInCredential() *credentials.GoogleSignInCredential {
	if x != nil {
		if x, ok := x.LoginMethod.(*LoginRequest_GoogleSignInCredential); ok {
			return x.GoogleSignInCredential
		}
	}
	return nil
}

type isLoginRequest_LoginMethod interface {
	isLoginRequest_LoginMethod()
}

type LoginRequest_StoredCredential struct {
	StoredCredential *credentials.StoredCredential `protobuf:"bytes,100,opt,name=stored_credential,json=storedCredential,proto3,oneof"`
}

type LoginRequest_Password struct {
	Password *credentials.Password `protobuf:"bytes,101,opt,name=password,proto3,oneof"`
}

type LoginRequest_FacebookAccessToken struct {
	FacebookAccessToken *credentials.FacebookAccessToken `protobuf:"bytes,102,opt,name=facebook_access_token,json=facebookAccessToken,proto3,oneof"`
}

type LoginRequest_PhoneNumber struct {
	PhoneNumber *identifiers.PhoneNumber `protobuf:"bytes,103,opt,name=phone_number,json=phoneNumber,proto3,oneof"`
}

type LoginRequest_OneTimeToken struct {
	OneTimeToken *credentials.OneTimeToken `protobuf:"bytes,104,opt,name=one_time_token,json=oneTimeToken,proto3,oneof"`
}

type LoginRequest_ParentChildCredential struct {
	ParentChildCredential *credentials.ParentChildCredential `protobuf:"bytes,105,opt,name=parent_child_credential,json=parentChildCredential,proto3,oneof"`
}

type LoginRequest_AppleSignInCredential struct {
	AppleSignInCredential *credentials.AppleSignInCredential `protobuf:"bytes,106,opt,name=apple_sign_in_credential,json=appleSignInCredential,proto3,oneof"`
}

type LoginRequest_SamsungSignInCredential struct {
	SamsungSignInCredential *credentials.SamsungSignInCredential `protobuf:"bytes,107,opt,name=samsung_sign_in_credential,json=samsungSignInCredential,proto3,oneof"`
}

type LoginRequest_GoogleSignInCredential struct {
	GoogleSignInCredential *credentials.GoogleSignInCredential `protobuf:"bytes,108,opt,name=google_sign_in_credential,json=googleSignInCredential,proto3,oneof"`
}

func (*LoginRequest_StoredCredential) isLoginRequest_LoginMethod() {}

func (*LoginRequest_Password) isLoginRequest_LoginMethod() {}

func (*LoginRequest_FacebookAccessToken) isLoginRequest_LoginMethod() {}

func (*LoginRequest_PhoneNumber) isLoginRequest_LoginMethod() {}

func (*LoginRequest_OneTimeToken) isLoginRequest_LoginMethod() {}

func (*LoginRequest_ParentChildCredential) isLoginRequest_LoginMethod() {}

func (*LoginRequest_AppleSignInCredential) isLoginRequest_LoginMethod() {}

func (*LoginRequest_SamsungSignInCredential) isLoginRequest_LoginMethod() {}

func (*LoginRequest_GoogleSignInCredential) isLoginRequest_LoginMethod() {}

type LoginOk struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Username             string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	AccessToken          string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	StoredCredential     []byte                 `protobuf:"bytes,3,opt,name=stored_credential,json=storedCredential,proto3" json:"stored_credential,omitempty"`
	AccessTokenExpiresIn int32                  `protobuf:"varint,4,opt,name=access_token_expires_in,json=accessTokenExpiresIn,proto3" json:"access_token_expires_in,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *LoginOk) Reset() {
	*x = LoginOk{}
	mi := &file_spotify_login5_v3_login5_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginOk) ProtoMessage() {}

func (x *LoginOk) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_login5_v3_login5_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginOk.ProtoReflect.Descriptor instead.
func (*LoginOk) Descriptor() ([]byte, []int) {
	return file_spotify_login5_v3_login5_proto_rawDescGZIP(), []int{5}
}

func (x *LoginOk) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginOk) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginOk) GetStoredCredential() []byte {
	if x != nil {
		return x.StoredCredential
	}
	return nil
}

func (x *LoginOk) GetAccessTokenExpiresIn() int32 {
	if x != nil {
		return x.AccessTokenExpiresIn
	}
	return 0
}

type LoginResponse struct {
	state           protoimpl.MessageState   `protogen:"open.v1"`
	Warnings        []LoginResponse_Warnings `protobuf:"varint,4,rep,packed,name=warnings,proto3,enum=spotify.login5.v3.LoginResponse_Warnings" json:"warnings,omitempty"`
	LoginContext    []byte                   `protobuf:"bytes,5,opt,name=login_context,json=loginContext,proto3" json:"login_context,omitempty"`
	IdentifierToken string                   `protobuf:"bytes,6,opt,name=identifier_token,json=identifierToken,proto3" json:"identifier_token,omitempty"`
	UserInfo        *UserInfo                `protobuf:"bytes,7,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	// Types that are valid to be assigned to Response:
	//
	//	*LoginResponse_Ok
	//	*LoginResponse_Error
	//	*LoginResponse_Challenges
	Response      isLoginResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_spotify_login5_v3_login5_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_login5_v3_login5_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_spotify_login5_v3_login5_proto_rawDescGZIP(), []int{6}
}

func (x *LoginResponse) GetWarnings() []LoginResponse_Warnings {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *LoginResponse) GetLoginContext() []byte {
	if x != nil {
		return x.LoginContext
	}
	return nil
}

func (x *LoginResponse) GetIdentifierToken() string {
	if x != nil {
		return x.IdentifierToken
	}
	return ""
}

func (x *LoginResponse) GetUserInfo() *UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

func (x *LoginResponse) GetResponse() isLoginResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *LoginResponse) GetOk() *LoginOk {
	if x != nil {
		if x, ok := x.Response.(*LoginResponse_Ok); ok {
			return x.Ok
		}
	}
	return nil
}

func (x *LoginResponse) GetError() LoginError {
	if x != nil {
		if x, ok := x.Response.(*LoginResponse_Error); ok {
			return x.Error
		}
	}
	return LoginError_UNKNOWN_ERROR
}

func (x *LoginResponse) GetChallenges() *Challenges {
	if x != nil {
		if x, ok := x.Response.(*LoginResponse_Challenges); ok {
			return x.Challenges
		}
	}
	return nil
}

type isLoginResponse_Response interface {
	isLoginResponse_Response()
}

type LoginResponse_Ok struct {
	Ok *LoginOk `protobuf:"bytes,1,opt,name=ok,proto3,oneof"`
}

type LoginResponse_Error struct {
	Error LoginError `protobuf:"varint,2,opt,name=error,proto3,enum=spotify.login5.v3.LoginError,oneof"`
}

type LoginResponse_Challenges struct {
	Challenges *Challenges `protobuf:"bytes,3,opt,name=challenges,proto3,oneof"`
}

func (*LoginResponse_Ok) isLoginResponse_Response() {}

func (*LoginResponse_Error) isLoginResponse_Response() {}

func (*LoginResponse_Challenges) isLoginResponse_Response() {}

var File_spotify_login5_v3_login5_proto protoreflect.FileDescriptor

const file_spotify_login5_v3_login5_proto_rawDesc = "" +
	"\n" +
	"\x1espotify/login5/v3/login5.proto\x12\x11spotify.login5.v3\x1a*spotify/login5/v3/login5_client_info.proto\x1a(spotify/login5/v3/login5_user_info.proto\x1a9spotify/login5/v3/challenges/login5_challenges_code.proto\x1a=spotify/login5/v3/challenges/login5_challenges_hashcash.proto\x1a6spotify/login5/v3/credentials/login5_credentials.proto\x1a6spotify/login5/v3/identifiers/login5_identifiers.proto\"J\n" +
	"\n" +
	"Challenges\x12<\n" +
	"\n" +
	"challenges\x18\x01 \x03(\v2\x1c.spotify.login5.v3.ChallengeR\n" +
	"challenges\"\xaa\x01\n" +
	"\tChallenge\x12M\n" +
	"\bhashcash\x18\x01 \x01(\v2/.spotify.login5.v3.challenges.HashcashChallengeH\x00R\bhashcash\x12A\n" +
	"\x04code\x18\x02 \x01(\v2+.spotify.login5.v3.challenges.CodeChallengeH\x00R\x04codeB\v\n" +
	"\tchallenge\"X\n" +
	"\x12ChallengeSolutions\x12B\n" +
	"\tsolutions\x18\x01 \x03(\v2$.spotify.login5.v3.ChallengeSolutionR\tsolutions\"\xaf\x01\n" +
	"\x11ChallengeSolution\x12L\n" +
	"\bhashcash\x18\x01 \x01(\v2..spotify.login5.v3.challenges.HashcashSolutionH\x00R\bhashcash\x12@\n" +
	"\x04code\x18\x02 \x01(\v2*.spotify.login5.v3.challenges.CodeSolutionH\x00R\x04codeB\n" +
	"\n" +
	"\bsolution\"\xde\b\n" +
	"\fLoginRequest\x12>\n" +
	"\vclient_info\x18\x01 \x01(\v2\x1d.spotify.login5.v3.ClientInfoR\n" +
	"clientInfo\x12#\n" +
	"\rlogin_context\x18\x02 \x01(\fR\floginContext\x12V\n" +
	"\x13challenge_solutions\x18\x03 \x01(\v2%.spotify.login5.v3.ChallengeSolutionsR\x12challengeSolutions\x12^\n" +
	"\x11stored_credential\x18d \x01(\v2/.spotify.login5.v3.credentials.StoredCredentialH\x00R\x10storedCredential\x12E\n" +
	"\bpassword\x18e \x01(\v2'.spotify.login5.v3.credentials.PasswordH\x00R\bpassword\x12h\n" +
	"\x15facebook_access_token\x18f \x01(\v22.spotify.login5.v3.credentials.FacebookAccessTokenH\x00R\x13facebookAccessToken\x12O\n" +
	"\fphone_number\x18g \x01(\v2*.spotify.login5.v3.identifiers.PhoneNumberH\x00R\vphoneNumber\x12S\n" +
	"\x0eone_time_token\x18h \x01(\v2+.spotify.login5.v3.credentials.OneTimeTokenH\x00R\foneTimeToken\x12n\n" +
	"\x17parent_child_credential\x18i \x01(\v24.spotify.login5.v3.credentials.ParentChildCredentialH\x00R\x15parentChildCredential\x12o\n" +
	"\x18apple_sign_in_credential\x18j \x01(\v24.spotify.login5.v3.credentials.AppleSignInCredentialH\x00R\x15appleSignInCredential\x12u\n" +
	"\x1asamsung_sign_in_credential\x18k \x01(\v26.spotify.login5.v3.credentials.SamsungSignInCredentialH\x00R\x17samsungSignInCredential\x12r\n" +
	"\x19google_sign_in_credential\x18l \x01(\v25.spotify.login5.v3.credentials.GoogleSignInCredentialH\x00R\x16googleSignInCredentialB\x0e\n" +
	"\flogin_method\"\xac\x01\n" +
	"\aLoginOk\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12+\n" +
	"\x11stored_credential\x18\x03 \x01(\fR\x10storedCredential\x125\n" +
	"\x17access_token_expires_in\x18\x04 \x01(\x05R\x14accessTokenExpiresIn\"\xd4\x03\n" +
	"\rLoginResponse\x12E\n" +
	"\bwarnings\x18\x04 \x03(\x0e2).spotify.login5.v3.LoginResponse.WarningsR\bwarnings\x12#\n" +
	"\rlogin_context\x18\x05 \x01(\fR\floginContext\x12)\n" +
	"\x10identifier_token\x18\x06 \x01(\tR\x0fidentifierToken\x128\n" +
	"\tuser_info\x18\a \x01(\v2\x1b.spotify.login5.v3.UserInfoR\buserInfo\x12,\n" +
	"\x02ok\x18\x01 \x01(\v2\x1a.spotify.login5.v3.LoginOkH\x00R\x02ok\x125\n" +
	"\x05error\x18\x02 \x01(\x0e2\x1d.spotify.login5.v3.LoginErrorH\x00R\x05error\x12?\n" +
	"\n" +
	"challenges\x18\x03 \x01(\v2\x1d.spotify.login5.v3.ChallengesH\x00R\n" +
	"challenges\"@\n" +
	"\bWarnings\x12\x13\n" +
	"\x0fUNKNOWN_WARNING\x10\x00\x12\x1f\n" +
	"\x1bDEPRECATED_PROTOCOL_VERSION\x10\x01B\n" +
	"\n" +
	"\bresponse*\xd3\x01\n" +
	"\n" +
	"LoginError\x12\x11\n" +
	"\rUNKNOWN_ERROR\x10\x00\x12\x17\n" +
	"\x13INVALID_CREDENTIALS\x10\x01\x12\x0f\n" +
	"\vBAD_REQUEST\x10\x02\x12\x1e\n" +
	"\x1aUNSUPPORTED_LOGIN_PROTOCOL\x10\x03\x12\v\n" +
	"\aTIMEOUT\x10\x04\x12\x16\n" +
	"\x12UNKNOWN_IDENTIFIER\x10\x05\x12\x15\n" +
	"\x11TOO_MANY_ATTEMPTS\x10\x06\x12\x17\n" +
	"\x13INVALID_PHONENUMBER\x10\a\x12\x13\n" +
	"\x0fTRY_AGAIN_LATER\x10\bB\xce\x01\n" +
	"\x15com.spotify.login5.v3B\vLogin5ProtoP\x01ZBgithub.com/devgianlu/go-librespot/proto/spotify/login5/v3;login5v3\xa2\x02\x03SLX\xaa\x02\x11Spotify.Login5.V3\xca\x02\x11Spotify\\Login5\\V3\xe2\x02\x1dSpotify\\Login5\\V3\\GPBMetadata\xea\x02\x13Spotify::Login5::V3b\x06proto3"

var (
	file_spotify_login5_v3_login5_proto_rawDescOnce sync.Once
	file_spotify_login5_v3_login5_proto_rawDescData []byte
)

func file_spotify_login5_v3_login5_proto_rawDescGZIP() []byte {
	file_spotify_login5_v3_login5_proto_rawDescOnce.Do(func() {
		file_spotify_login5_v3_login5_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spotify_login5_v3_login5_proto_rawDesc), len(file_spotify_login5_v3_login5_proto_rawDesc)))
	})
	return file_spotify_login5_v3_login5_proto_rawDescData
}

var file_spotify_login5_v3_login5_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_spotify_login5_v3_login5_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_spotify_login5_v3_login5_proto_goTypes = []any{
	(LoginError)(0),                             // 0: spotify.login5.v3.LoginError
	(LoginResponse_Warnings)(0),                 // 1: spotify.login5.v3.LoginResponse.Warnings
	(*Challenges)(nil),                          // 2: spotify.login5.v3.Challenges
	(*Challenge)(nil),                           // 3: spotify.login5.v3.Challenge
	(*ChallengeSolutions)(nil),                  // 4: spotify.login5.v3.ChallengeSolutions
	(*ChallengeSolution)(nil),                   // 5: spotify.login5.v3.ChallengeSolution
	(*LoginRequest)(nil),                        // 6: spotify.login5.v3.LoginRequest
	(*LoginOk)(nil),                             // 7: spotify.login5.v3.LoginOk
	(*LoginResponse)(nil),                       // 8: spotify.login5.v3.LoginResponse
	(*challenges.HashcashChallenge)(nil),        // 9: spotify.login5.v3.challenges.HashcashChallenge
	(*challenges.CodeChallenge)(nil),            // 10: spotify.login5.v3.challenges.CodeChallenge
	(*challenges.HashcashSolution)(nil),         // 11: spotify.login5.v3.challenges.HashcashSolution
	(*challenges.CodeSolution)(nil),             // 12: spotify.login5.v3.challenges.CodeSolution
	(*ClientInfo)(nil),                          // 13: spotify.login5.v3.ClientInfo
	(*credentials.StoredCredential)(nil),        // 14: spotify.login5.v3.credentials.StoredCredential
	(*credentials.Password)(nil),                // 15: spotify.login5.v3.credentials.Password
	(*credentials.FacebookAccessToken)(nil),     // 16: spotify.login5.v3.credentials.FacebookAccessToken
	(*identifiers.PhoneNumber)(nil),             // 17: spotify.login5.v3.identifiers.PhoneNumber
	(*credentials.OneTimeToken)(nil),            // 18: spotify.login5.v3.credentials.OneTimeToken
	(*credentials.ParentChildCredential)(nil),   // 19: spotify.login5.v3.credentials.ParentChildCredential
	(*credentials.AppleSignInCredential)(nil),   // 20: spotify.login5.v3.credentials.AppleSignInCredential
	(*credentials.SamsungSignInCredential)(nil), // 21: spotify.login5.v3.credentials.SamsungSignInCredential
	(*credentials.GoogleSignInCredential)(nil),  // 22: spotify.login5.v3.credentials.GoogleSignInCredential
	(*UserInfo)(nil),                            // 23: spotify.login5.v3.UserInfo
}
var file_spotify_login5_v3_login5_proto_depIdxs = []int32{
	3,  // 0: spotify.login5.v3.Challenges.challenges:type_name -> spotify.login5.v3.Challenge
	9,  // 1: spotify.login5.v3.Challenge.hashcash:type_name -> spotify.login5.v3.challenges.HashcashChallenge
	10, // 2: spotify.login5.v3.Challenge.code:type_name -> spotify.login5.v3.challenges.CodeChallenge
	5,  // 3: spotify.login5.v3.ChallengeSolutions.solutions:type_name -> spotify.login5.v3.ChallengeSolution
	11, // 4: spotify.login5.v3.ChallengeSolution.hashcash:type_name -> spotify.login5.v3.challenges.HashcashSolution
	12, // 5: spotify.login5.v3.ChallengeSolution.code:type_name -> spotify.login5.v3.challenges.CodeSolution
	13, // 6: spotify.login5.v3.LoginRequest.client_info:type_name -> spotify.login5.v3.ClientInfo
	4,  // 7: spotify.login5.v3.LoginRequest.challenge_solutions:type_name -> spotify.login5.v3.ChallengeSolutions
	14, // 8: spotify.login5.v3.LoginRequest.stored_credential:type_name -> spotify.login5.v3.credentials.StoredCredential
	15, // 9: spotify.login5.v3.LoginRequest.password:type_name -> spotify.login5.v3.credentials.Password
	16, // 10: spotify.login5.v3.LoginRequest.facebook_access_token:type_name -> spotify.login5.v3.credentials.FacebookAccessToken
	17, // 11: spotify.login5.v3.LoginRequest.phone_number:type_name -> spotify.login5.v3.identifiers.PhoneNumber
	18, // 12: spotify.login5.v3.LoginRequest.one_time_token:type_name -> spotify.login5.v3.credentials.OneTimeToken
	19, // 13: spotify.login5.v3.LoginRequest.parent_child_credential:type_name -> spotify.login5.v3.credentials.ParentChildCredential
	20, // 14: spotify.login5.v3.LoginRequest.apple_sign_in_credential:type_name -> spotify.login5.v3.credentials.AppleSignInCredential
	21, // 15: spotify.login5.v3.LoginRequest.samsung_sign_in_credential:type_name -> spotify.login5.v3.credentials.SamsungSignInCredential
	22, // 16: spotify.login5.v3.LoginRequest.google_sign_in_credential:type_name -> spotify.login5.v3.credentials.GoogleSignInCredential
	1,  // 17: spotify.login5.v3.LoginResponse.warnings:type_name -> spotify.login5.v3.LoginResponse.Warnings
	23, // 18: spotify.login5.v3.LoginResponse.user_info:type_name -> spotify.login5.v3.UserInfo
	7,  // 19: spotify.login5.v3.LoginResponse.ok:type_name -> spotify.login5.v3.LoginOk
	0,  // 20: spotify.login5.v3.LoginResponse.error:type_name -> spotify.login5.v3.LoginError
	2,  // 21: spotify.login5.v3.LoginResponse.challenges:type_name -> spotify.login5.v3.Challenges
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_spotify_login5_v3_login5_proto_init() }
func file_spotify_login5_v3_login5_proto_init() {
	if File_spotify_login5_v3_login5_proto != nil {
		return
	}
	file_spotify_login5_v3_login5_client_info_proto_init()
	file_spotify_login5_v3_login5_user_info_proto_init()
	file_spotify_login5_v3_login5_proto_msgTypes[1].OneofWrappers = []any{
		(*Challenge_Hashcash)(nil),
		(*Challenge_Code)(nil),
	}
	file_spotify_login5_v3_login5_proto_msgTypes[3].OneofWrappers = []any{
		(*ChallengeSolution_Hashcash)(nil),
		(*ChallengeSolution_Code)(nil),
	}
	file_spotify_login5_v3_login5_proto_msgTypes[4].OneofWrappers = []any{
		(*LoginRequest_StoredCredential)(nil),
		(*LoginRequest_Password)(nil),
		(*LoginRequest_FacebookAccessToken)(nil),
		(*LoginRequest_PhoneNumber)(nil),
		(*LoginRequest_OneTimeToken)(nil),
		(*LoginRequest_ParentChildCredential)(nil),
		(*LoginRequest_AppleSignInCredential)(nil),
		(*LoginRequest_SamsungSignInCredential)(nil),
		(*LoginRequest_GoogleSignInCredential)(nil),
	}
	file_spotify_login5_v3_login5_proto_msgTypes[6].OneofWrappers = []any{
		(*LoginResponse_Ok)(nil),
		(*LoginResponse_Error)(nil),
		(*LoginResponse_Challenges)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spotify_login5_v3_login5_proto_rawDesc), len(file_spotify_login5_v3_login5_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spotify_login5_v3_login5_proto_goTypes,
		DependencyIndexes: file_spotify_login5_v3_login5_proto_depIdxs,
		EnumInfos:         file_spotify_login5_v3_login5_proto_enumTypes,
		MessageInfos:      file_spotify_login5_v3_login5_proto_msgTypes,
	}.Build()
	File_spotify_login5_v3_login5_proto = out.File
	file_spotify_login5_v3_login5_proto_goTypes = nil
	file_spotify_login5_v3_login5_proto_depIdxs = nil
}
